### ISSUE TITLE
small issue with slc and loopback

### ISSUE THREAD

**Issue by mschmulen** [strongloop/strongloop#107]
Having a small issue with slc and loopback ( Mon Feb 17 11:29:14 CST 2014 )

running the commands:

```
slc lb project node-server
cd node-server
npm install
```

Results with the following error:

```
660 matt:node-server$ npm install
npm WARN package.json node-server@0.0.0 No description
npm WARN package.json node-server@0.0.0 No repository field.
npm WARN package.json node-server@0.0.0 No README data
npm ERR! peerinvalid The package loopback does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer loopback-explorer@1.1.0 wants loopback@1.x >=1.5
npm ERR! peerinvalid Peer loopback-push-notification@1.1.1 wants loopback@1.x >=1.6.1

npm ERR! System Darwin 13.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/matt/scratch/monday/node-server
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! code EPEERINVALID
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/matt/scratch/monday/node-server/npm-debug.log
npm ERR! not ok code 0
661 matt:node-server$
```

not sure what the issue is, any help appreciated .

M.

**Comment by denzelwamburu** [comment]
Am having the same issue when installing Strongloop in my ubuntu machine.Give some error,actually i think it is installing partially but the command 'slc' is not recognized ,how do i fix this :(

**Comment by rmg** [comment]
@denzelwamburu what is the error you are seeing? Did you uninstall the conflicting packages?

**Comment by denzelwamburu** [comment]
@rmg i managed to make it run but i had to manually delete some file in usr/bin (or something like that) the installer was unable to do it automatically.Guess the file was placed they by previous installation.
