### ISSUE TITLE
Error: listen EPERM using sharefolder on VirtualBox

### ISSUE THREAD

**Issue by ariskemper** [strongloop/strongloop#179]
slc version 2.9.2

slc run --cluster=1 app.js

Error: listen EPERM
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1023:19)
    at listen (net.js:1064:10)
    at Server.listen (net.js:1132:5)
    at Server.listen (/root/.nvm/v0.10.32/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-control-channel/lib/server.js:70:6)
    at Object.start (/root/.nvm/v0.10.32/lib/node_modules/strongloop/node_modules/strong-supervisor/lib/runctl.js:65:10)
    at EventEmitter.<anonymous> (/root/.nvm/v0.10.32/lib/node_modules/strongloop/node_modules/strong-supervisor/lib/config.js:236:12)
    at EventEmitter.emit (events.js:92:17)
    at /root/.nvm/v0.10.32/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-cluster-control/lib/master.js:382:10
    at process._tickCallback (node.js:419:13)

Description:
Runing on debian wheezy with sharing projects from host to guest with shared folders in Virtualbbox. Command runs as root and permissions and user is root, group is vboxsf.

**Comment by sam-github** [comment]
Blocked on a strong-supervisor release of https://github.com/strongloop/strong-supervisor/pull/82, which make --control work again.

**Comment by kraman** [comment]
@ariskemper An option you might consider is running you app under strong-pm (`slc pm`) on the root (non-shared) filesystem and then controlled it over HTTP. It would get around any limitations of the shared filesystem.

See http://docs.strongloop.com/display/public/SLC/slc+pmctl

**Comment by adanielyan** [comment]
I'm trying to setup a development environment on my local Windows 7 machine using vagrant and vbox and get the error described here. I spent almost a week trying different permissions, vagrant configurations and sharing options. But none of them worked so far. I tried vbox native sharing, as well as samba and nfs, but still get the ```Error: listen EPERM``` error. I either can run ```slc arc``` but cannot share the folder with my code or I can share but can't run ```slc arc```. The ```slc run .``` works fine though. 

So I'd like to know if anybody was able to make it work if there is any solution at all.

**Comment by adanielyan** [comment]
I found a more or less working solution. Instead of sharing a folder from host I ended up installing samba server on my guest Ubuntu and sharing a folder on my guest so I can access it from my Windows host. The downside is that the vbox should be running in order to have access to files. If I shut it down or restart I will loose access to the guest machine and my code files and my phpStorm freezes.

**Comment by adanielyan** [comment]
I ended up creating two synced folders. One folder ```/home/vagrant/www``` on my guest machine syncs with the folder on host machine ```./projects```and then there is another folder on my guest ```/var/www``` that syncs with ```/home/vagrant/www```. I edit code on the host machine and it gets synced with the ```/var/www``` through ```/home/vagrant/www```. Then I can run ```slc arc .``` or any other slc command in ```/var/www``` without any issues.

I created Vagrant configuration that sets up everything automatically for me. The configuration can be found here: https://github.com/adanielyan/loopback-vagrant.

This is probably not the best possible solution but it works for me just fine. Hope it will help anybody who has the same issue.

In fact this Vagrant configuration can be helpful even without the sync workaround. Just comment out lines 57 - 86 in ```script.sh``` to disable the unison sync for ```/home/vagrant/www``` and ```/var/www``` folders on guest machine.

**Comment by rmg** [comment]
@adanielyan you may also be interested in https://github.com/strongloop-community/strongbox or https://github.com/strongloop-community/vagrant-strongnode-mongodb

Or as another starting point for your box, I recently created a [strongloop box](https://atlas.hashicorp.com/strongloop/boxes/node-trusty) that you can get with `vagrant up strongloop/node-trusty --provider virtualbox`

They aren't maintained to the same level as our modules, but if you are already writing your own Vagrantfile's you may find them useful.

**Comment by adanielyan** [comment]
Thanks for sharing! Your configuration files look pretty decent. One difference I noticed and I think is worth mentioning is that in my configuration I install node as vagrant user, not as root. According to some resources it is a better approach.

Also, I noticed this line in your second config option:
```vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]```
I had this line in my configuration at first but didn't notice any difference on Windows host. It didn't solve the symlinks error when running ```npm install``` without ```--no-bin-links```. Can you please explain what it does?
