### ISSUE TITLE
Improve READMEs

### ISSUE THREAD

**Issue by chandadharap** [strongloop/strongloop#191]
There are three basic classes of repo, I tried to make the READMEs consistent in structure *within a class*.

Top-level packages are described in some detail, and link to strongloop as the CLI/GUI, and to there mini-sites (loopback.io and strong-pm.io):

- process manager, aka strong-pm
- loopback

The common top-level installable is:

- strongloop

It links to both mini sites.

Top-level commands link to strongloop, and to the mini site:

- arc (a special case, its the GUI equivalent of all the other slc commands)
- build
- deploy
- start
- registry
- run/runctl

***NOTE: after dredging through these, I'm mostly convinced we should be spending time on anything but the most important top-level READMEs: loopback, strong-pm, strongloop ... everything else is too time consuming, and low-value. ***

Some ongoing discussion of [blog vs docs vs strong-pm.io](https://docs.google.com/a/strongloop.com/document/d/1Ab9pd0MKbOY_kgM6NtD2Ez-P95rZ_-K769_rpxp8ngo)

**Comment by sam-github** [comment]
@ijroth can you take a look at above? Most of the low-level readmes just point to strong-pm and strongloop, but take a look particularly at strongloop/strong-pm#157 and its feature list.
