### ISSUE TITLE
Update "slc run" console messages : decprecate strongops

### ISSUE THREAD

**Issue by crandmck** [strongloop/strongloop#192]
```
$ slc run
INFO strong-agent API key not found, StrongOps dashboard reporting disabled.
Generate configuration with:
    npm install -g strongloop
    slc strongops
See http://docs.strongloop.com/strong-agent for more information.
```
Since StrongOps hosted monitoring is [being deprecated](https://github.com/strongloop-internal/scrum-loopback/issues/154) (and eventually EOLed), this message should no longer refer to StrongOps dashboard.   Also, http://docs.strongloop.com/strong-agent redirects to an old page (which I've redirected to the new page) but we should remove the double redirect at some point.

@chandadharap @ijroth 
Need to think about what the message should say in general.

**Comment by sam-github** [comment]
We can't drop the first line, if we did, StrongOps users would get completely silent failure when they have misconfigured their API key or app name.

The last 4 lines are noise now, and we can just delete.

**Comment by chandadharap** [comment]
Hi, Am not sure we agreed to drop it from command line before Node Summit. That means more release churn in two days. @ijroth  for comment.

**Comment by sam-github** [comment]
https://github.com/strongloop/strongops/commits/master

^--- there are no other commits in strong-agent master ATM pending publish. That means that deleting 4 console.logs and re-releasing is the work of 10 minutes, and is so low risk I don't even know if it needs QE.

Your call.

Cf. https://github.com/strongloop/strongops/blob/master/agent/lib/agent.js#L77-L83

**Comment by chandadharap** [comment]
Do NOT drop it from commandline at this moment please. There are open questions and answers in another thread. We CANNOT take this out from slc today. Please backlog this issue.

**Comment by ijroth** [comment]
For a replacement message, how about we advertise a little for Arc:

Running with strong-agent enabled. To see metrics, use profiler and other diagnostic features run:
# slc arc

**Comment by sam-github** [comment]
```
$ slc run
INFO strong-agent API key not found, StrongOps dashboard reporting disabled.
Generate configuration with:
    npm install -g strongloop
    slc strongops
See http://docs.strongloop.com/strong-agent for more information.
```

Above text should become what, exactly?

**Comment by sam-github** [comment]
I can invent something, but if someone provides me exact text, its easier, I can put it in in a few minutes.

**Comment by chandadharap** [comment]
Issac said earlier here:

Running with strong-agent enabled. To see metrics, use profiler and other diagnostic features run:
slc arc

**Comment by sam-github** [comment]
This is `slc run`. It doesn't work with `slc arc`, so this message won't work:

> Running with strong-agent enabled. To see metrics, use profiler and other diagnostic features run:
slc arc

@chandadharap perhaps the `To see metrics, use profiler and other diagnostic features run:
slc arc` should be in this PR:
https://github.com/strongloop/strong-start/pull/7/files

I re-make my suggestion here: https://github.com/strongloop/strongloop/issues/192#issuecomment-72719902.

It gives the minimal notification that an API key was not found and has no other text.

Note that most people will be using `slc start` (and we are removing explicit usage of `slc run` from most of our docs), so this message isn't so relevant, other than it is verbose and misleading.

Lets just delete the misleading text and move on.

**Comment by chandadharap** [comment]
Sam and I discussed. i agree. Will catch up with Issac later. Please make the change.
