### ISSUE TITLE
error when installing strongloop

### ISSUE THREAD

**Issue by bingeh** [strongloop/strongloop#200]
I install strongloop with command `npm install -g strongloop`, but it always show the error

'
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.12.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/node/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/heapdump/.node-gyp"
'
and I try to use command  `export USER=root && sudo npm install -g strongloop`, the error still remains.

**Comment by rmg** [comment]
@hzb can you share the full error output? The lines you have included is only showing a warning that would _not_ cause the installation to fail.

**Comment by bingeh** [comment]
@rmg thanks, here is the full error output

`
[root@localhost node-v0.12.0]# export USER=root && sudo npm install -g strongloop
npm WARN engine npm@1.4.28: wanted: {"node":">=0.8","npm":"1"} (current: {"node":"0.12.0","npm":"2.5.1"})
 
> heapdump@0.2.10 install /usr/local/node/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/heapdump
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.12.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/node/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/heapdump/.node-gyp"
child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/usr/local/node/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/heapdump/build'
  CXX(target) Release/obj.target/heapdump/src/heapdump.o
  CXX(target) Release/obj.target/heapdump/src/platform-posix.o
  SOLINK_MODULE(target) Release/obj.target/heapdump.node
  SOLINK_MODULE(target) Release/obj.target/heapdump.node: Finished
  COPY Release/heapdump.node
make: Leaving directory `/usr/local/node/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/heapdump/build'
 
> strong-fork-syslog@1.2.3 install /usr/local/node/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-fork-syslog
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.12.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/node/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-fork-syslog/.node-gyp"
child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/usr/local/node/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-fork-syslog/build'
  CXX(target) Release/obj.target/syslog/syslog.o
  SOLINK_MODULE(target) Release/obj.target/syslog.node
  SOLINK_MODULE(target) Release/obj.target/syslog.node: Finished
  COPY Release/syslog.node
make: Leaving directory `/usr/local/node/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-fork-syslog/build'
\
> strong-agent@1.3.2 install /usr/local/node/lib/node_modules/strongloop/node_modules/strong-agent
> node-gyp rebuild || exit 0

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.12.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/node/lib/node_modules/strongloop/node_modules/strong-agent/.node-gyp"
child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/usr/local/node/lib/node_modules/strongloop/node_modules/strong-agent/build'
  CXX(target) Release/obj.target/strong-agent/src/strong-agent.o
In file included from ../src/strong-agent.cc:15:0:
../src/watchdog.h: In function 'void strongloop::agent::watchdog::PatchSyscall()':
../src/watchdog.h:149:52: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   *reinterpret_cast<volatile uint64_t*>(address + 0) = 0xF8EBFAEBFCEBFEEBULL;
                                                    ^
../src/watchdog.h:178:52: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   *reinterpret_cast<volatile uint32_t*>(address + 0) =  // movabs $0, %rax
                                                    ^
../src/watchdog.h:179:75: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
       0xB848 | (0xFFFF0000 & *reinterpret_cast<volatile uint32_t*>(address));
                                                                           ^
  SOLINK_MODULE(target) Release/obj.target/strong-agent.node
  SOLINK_MODULE(target) Release/obj.target/strong-agent.node: Finished
  COPY Release/strong-agent.node
make: Leaving directory `/usr/local/node/lib/node_modules/strongloop/node_modules/strong-agent/build'
npm WARN engine async-listener@0.5.0: wanted: {"node":"<=0.11.8"} (current: {"node":"0.12.0","npm":"2.5.1"})
npm WARN engine async-listener@0.5.0: wanted: {"node":"<=0.11.8"} (current: {"node":"0.12.0","npm":"2.5.1"})
\
> ws@0.4.32 install /usr/local/node/lib/node_modules/strongloop/node_modules/node-inspector/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/usr/local/node/lib/node_modules/strongloop/node_modules/node-inspector/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/usr/local/node/lib/node_modules/strongloop/node_modules/node-inspector/node_modules/ws/build'
 
> ws@0.4.32 install /usr/local/node/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/usr/local/node/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/usr/local/node/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/ws/build'
npm WARN engine async-listener@0.5.0: wanted: {"node":"<=0.11.8"} (current: {"node":"0.12.0","npm":"2.5.1"})
 
> ws@0.5.0 install /usr/local/node/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/strong-mesh-client/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/usr/local/node/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/strong-mesh-client/node_modules/engine.io/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/usr/local/node/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/strong-mesh-client/node_modules/engine.io/node_modules/ws/build'
/usr/local/node/bin/lb-ng -> /usr/local/node/lib/node_modules/strongloop/node_modules/loopback-sdk-angular-cli/bin/lb-ng
/usr/local/node/bin/lb-ng-doc -> /usr/local/node/lib/node_modules/strongloop/node_modules/loopback-sdk-angular-cli/bin/lb-ng-doc
/usr/local/node/bin/slc -> /usr/local/node/lib/node_modules/strongloop/bin/slc
strongloop@2.10.3 /usr/local/node/lib/node_modules/strongloop
├── sl-blip@1.0.0
├── which@1.0.9
├── ini@1.3.3
├── inflection@1.6.0
├── async@0.9.0
├── read@1.0.5 (mute-stream@0.0.4)
├── debug@2.1.2 (ms@0.7.0)
├── nopt@3.0.1 (abbrev@1.0.5)
├── cpr@0.3.3 (rimraf@2.2.8, graceful-fs@3.0.5)
├── colors@1.0.3
├── mkdirp@0.5.0 (minimist@0.0.8)
├── is2@0.0.13 (deep-is@0.1.2)
├── optimist@0.6.1 (wordwrap@0.0.2, minimist@0.0.10)
├── fs.extra@1.2.1 (mkdirp@0.3.5, walk@2.2.1, fs-extra@0.6.4)
├── strong-deploy@1.1.4 (posix-getopt@1.1.0, shelljs@0.3.0)
├── json-file-plus@2.0.0 (is@2.0.2, node.extend@1.1.3, promiseback@2.0.1)
├── prompt@0.2.14 (revalidator@0.1.8, pkginfo@0.3.0, utile@0.2.1, winston@0.8.3)
├── strong-registry@1.1.4 (osenv@0.0.3, commander@2.6.0, rimraf@2.2.8, semver@2.3.2, bluebird@1.2.4, inquirer@0.4.1)
├── strong-build@1.0.3 (posix-getopt@1.1.0, shelljs@0.3.0, json-file-plus@1.0.7, vasync@1.6.2, lodash@2.4.1)
├── strong-agent@1.3.2 (strong-license@1.0.2, semver@2.2.1)
├── strong-supervisor@1.4.1 (dotenv@0.2.8, posix-getopt@1.1.0, heapdump@0.2.10, strong-control-channel@1.1.2, strong-statsd@2.0.2, strong-npm-ls@1.0.5, strong-fork-syslog@1.2.3, strong-log-transformer@1.0.1, strong-cluster-control@2.0.0)
├── loopback-workspace@2.6.0 (rimraf@2.2.8, temp@0.8.1, debug@1.0.4, uuid@1.4.2, express@3.20.1, loopback-datasource-juggler@1.7.1, loopback@1.10.0)
├── strong-pm@1.7.2 (uid-number@0.0.5, npm-path@1.0.1, extsprintf@1.2.1, posix-getopt@1.1.0, passwd-user@1.1.0, strong-mesh-models@3.0.1, serve-favicon@2.2.0, bl@0.9.4, concat-stream@1.4.7, strong-fork-cicada@1.1.2, errorhandler@1.3.4, compression@1.4.1, strong-control-channel@1.1.2, tar@1.0.3, loopback-boot@2.6.5, lodash@2.4.1, strong-npm-ls@1.0.5, http-auth@2.2.5, strong-service-install@1.1.2, loopback-datasource-juggler@2.18.1, loopback@2.13.0, loopback-explorer@1.7.1)
├── generator-loopback@1.7.3 (chalk@0.5.1, yosay@1.0.2, request@2.53.0, loopback-swagger@2.0.0, yeoman-generator@0.18.9, loopback-workspace@3.10.0)
├── npm@1.4.28
├── node-inspector@0.7.4 (opener@1.3.0, debug@0.8.1, async@0.8.0, rc@0.3.5, strong-data-uri@0.1.1, yargs@1.2.6, glob@3.2.11, express@4.0.0, ws@0.4.32)
├── loopback-sdk-angular-cli@1.1.4 (semver@2.3.2, loopback-sdk-angular@1.3.7, express@3.20.1, docular@0.6.6)
└── strong-arc@1.1.0 (opener@1.4.0, cookie-parser@1.3.4, split@0.3.3, fs-extra@0.14.0, http-proxy@1.8.1, serve-favicon@2.2.0, express@4.8.8, errorhandler@1.2.4, request@2.53.0, loopback-boot@2.6.5, ws@0.4.32, loopback-datasource-juggler@2.18.1, express-jsxtransform@1.1.0, loopback@2.13.0, strong-mesh-client@1.3.4, loopback-workspace@3.10.0)
`

**Comment by rmg** [comment]
Your output shows a few non-fatal warnings, but is otherwise successful.

Are you able to run `slc --version`?

Unfortunately there is nothing we can do about those warnings from inside the package. You could run `rm -rf ~/.node-gyp` and re-run the install and it _might_ clear up the permission issue, but it may come back depending on your usage of `sudo`.

**Comment by bingeh** [comment]
@rmg get error `-bash: slc: command not found` when run  `slc --version`, thanks.

**Comment by rmg** [comment]
How did you install node? You appear to be using a custom install location that requires adding `/usr/local/node/bin` to your $PATH. Have you done so?

How did you install `npm`? What is the output of `which npm`?

**Comment by rmg** [comment]
Forgot to add, `/usr/local/node/bin/slc --version` should work for you, but you will need to specify the full path each time unless you add `/usr/local/node/bin` to your $PATH.

**Comment by bingeh** [comment]
@rmg Thanks, but I reinstall all things, such as node.js npm, but still this error.

**Comment by rmg** [comment]
@hzb _how_ did you install node and npm? If you are using an installer it should be adding `/usr/local/node/bin` to your PATH. If you are not using an installer then the instructions you are following should tell you how to set your PATH environment variable appropriately.

**Comment by bingeh** [comment]
@rmg thanks, and I test this on ubuntu, it works now, I test it on centos, I will get the error above. Thanks again.

**Comment by RV2013** [comment]
I install strongloop with command "sudo npm install -g strongloop", but it always stuck at the last para shown below. The stick keeps on spinning but no updates till an hour. I tried this twice. Any idea what is wrong OR does installation takes a much long time ?

Here is my terminal's console log 

==================================================
npm WARN engine npm@1.4.28: wanted: {"node":">=0.8","npm":"1"} (current: {"node":"0.12.0","npm":"2.5.1"})
 
> strong-agent@1.3.2 install /usr/local/lib/node_modules/strongloop/node_modules/strong-agent
> node-gyp rebuild || exit 0

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/strong-agent/src/strong-agent.o
  SOLINK_MODULE(target) Release/strong-agent.node
  SOLINK_MODULE(target) Release/strong-agent.node: Finished
 
> heapdump@0.2.10 install /usr/local/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/heapdump
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/heapdump/src/heapdump.o
  CXX(target) Release/obj.target/heapdump/src/platform-posix.o
  SOLINK_MODULE(target) Release/heapdump.node
  SOLINK_MODULE(target) Release/heapdump.node: Finished
 
> strong-fork-syslog@1.2.3 install /usr/local/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-fork-syslog
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/syslog/syslog.o
  SOLINK_MODULE(target) Release/syslog.node
  SOLINK_MODULE(target) Release/syslog.node: Finished
 
> ws@0.4.32 install /usr/local/lib/node_modules/strongloop/node_modules/node-inspector/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
 
> ws@0.4.32 install /usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
|

==================================================
