### ISSUE TITLE
slc loopback:* not showing models from other folders present on model-config.json

### ISSUE THREAD

**Issue by lius** [strongloop/strongloop#202]
I'm organising the models in subfolders inside common/models, registering each one on model-config.json (_meta.sources property). The application runs and works fine, but these models are not showed on slc loopback:* commands, just the others ones (default from LB).

strongloop: 2.10.3
loopback: 2.13.0
juggler: 2.19.0

**Comment by lius** [comment]
Up. Should I open this issue on loopback repo?

**Comment by rmg** [comment]
@lius sorry for the slow response.

You should file this one against [generator-loopback](https://github.com/strongloop/generator-loopback/issues).
