### ISSUE TITLE
Installation on Mac osx stucks at certain point

### ISSUE THREAD

**Issue by RV2013** [strongloop/strongloop#205]
I am installing strongloop using command "sudo npm install -g strongloop". after setting all right permission for root user. 
every time the installations stucks at the last para shown below as my Treminal's log 

==================================================
export USER=root && sudo npm install -g strongloop
Password:
npm WARN engine npm@1.4.28: wanted: {"node":">=0.8","npm":"1"} (current: {"node":"0.12.0","npm":"2.5.1"})
 
> heapdump@0.2.10 install /usr/local/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/heapdump
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/heapdump/src/heapdump.o
  CXX(target) Release/obj.target/heapdump/src/platform-posix.o
  SOLINK_MODULE(target) Release/heapdump.node
  SOLINK_MODULE(target) Release/heapdump.node: Finished
 
> strong-fork-syslog@1.2.3 install /usr/local/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-fork-syslog
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/syslog/syslog.o
  SOLINK_MODULE(target) Release/syslog.node
  SOLINK_MODULE(target) Release/syslog.node: Finished
 
> strong-agent@1.3.2 install /usr/local/lib/node_modules/strongloop/node_modules/strong-agent
> node-gyp rebuild || exit 0

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/strong-agent/src/strong-agent.o
  SOLINK_MODULE(target) Release/strong-agent.node
  SOLINK_MODULE(target) Release/strong-agent.node: Finished
 
> ws@0.4.32 install /usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
 
> ws@0.4.32 install /usr/local/lib/node_modules/strongloop/node_modules/node-inspector/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
 
> ws@0.5.0 install /usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/strong-mesh-client/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
  \
==================================================

Q: Does it normally takes this long for installation OR could there be some issue ?

**Comment by rmg** [comment]
The installation can definitely take a while if your connection, CPU, or disk are slow. You could try adding `--verbose` to your install command to get a better idea of where it is in the installation when it gets stuck.

**Comment by sam-github** [comment]
Why are you using `export USER=root`?

It does not usually take this long, and mostly likely indicates a problem in your system's configuration.

I recommend following the OS X install directions from our docs: http://docs.strongloop.com/display/SL/_Installation

Also, some basic trouble-shooting info would be helpful:
- node -v
- npm -v
- `npm install -g heapdump`: does this work?

**Comment by RV2013** [comment]
Ok. Let me follow the instructions at : http://docs.strongloop.com/display/SL/_Installation.

Now i am trying with command :  sudo npm -g --unsafe-perm install strongloop

I realy dont know what exactly command "export USER=root" does but it was mentioned somewhere in issues and I have followed that.

**Comment by RV2013** [comment]
Ok. I followed the instructions and tried several time though I failed with the OSX terminal not progressing after certain level. 

Well, I was just curious to know an alternative way to install strongloop suite on mac osx as the command npm install -g --verbose strongloop does not finish successfully and hangs in between before it is finished.

It would be of great help to me if you can let me know below information .

1)  List all the npm modules with their respective source link (npm OR Github) to Download and install manually ...
2) Also let me know which modules needs to be stored where ... any specific directory structure OR tree ?
3) Finally, any script that needs to be run...

So in and all, I wont to break down the whole process done by  command -"npm install -g..." and instead prefer to install all required components,libraries and modules manually inside the designated directory/folder/structure...

**Comment by rmg** [comment]
Sorry I wasn't more clear. The purpose of the `--verbose` flag was for you to be able to see what part of the installation npm was getting stuck on and ideally tell us so that we can investigate. It was not intended to be a solution.

There are no directory structure requirements other than those required by node and npm. The module dependencies are all listed on the [npm module page](https://www.npmjs.com/package/strongloop) as well as in the [package.json in this repo](https://github.com/strongloop/strongloop/blob/master/package.json).

As for which of those modules you need to install, that will depend on which commands you want to use.

 * `slc arc` -> `npm install -g strong-arc` and run `sl-arc`
 * `slc run` -> `npm install -g strong-supervisor` and run `sl-run`
 * `slc build` -> `npm install -g strong-build` and run `sl-build`
 * `slc deploy` -> `npm install -g strong-deploy` and run `sl-deploy`
 * `slc pm` -> `npm install -g strong-pm` and run `sl-pm`

If you are asking how to install an npm module _without using npm_, then that is a much different task. For that I would recommend consulting the npm documentation on [folder structure](https://docs.npmjs.com/files/folders) and [package layout](https://docs.npmjs.com/files/package.json).

**Comment by RV2013** [comment]
I know the installation of various modules via npm and there isn't other way of installing except using npm. I agree to that. What exactly I want to find out is the placing of the modules inside specific directory like "/usr/local/lib/node_modules/strongloop/..." etc.. Do i need to manuaaly create the directory and follow the structure ?

**Comment by sam-github** [comment]
@RV2013 If you can't install strongloop on OS X, you have a problem in your system setup or have hit an npm bug in the . strongloop is a very generic npm package, with no install scripts, peer dependencies, etc. It does have a large number of dependencies, which sometimes exposes bugs in npm.

I would suggest updating your npm. Do an `npm install -g npm` to update to the latest, stable, npm version, and then retry installing strongloop.

**Comment by opadillaintegrify** [comment]
I'm also having problems installing strongloop on my mac.  It's productive for about 7 minutes and then comes to a complete halt.

I updated npm before my latest attempt at installation.
node v0.12.1
npm v2.8.3

As suggested in http://docs.strongloop.com/display/SL/Installing+StrongLoop#InstallingStrongLoop-MacOSX, I ran these commands beforehand:
sudo chown -R $USER /usr/local/bin
sudo chown -R $USER /usr/local/lib/node_modules

And then...
npm install -g strongloop --verbose

It was churning out messages for about 7 minutes and then came to a halt.  The last messages printed to the console are:

npm info attempt registry request try #3 at 1:40:34 PM
npm verb etag "79XQA3ZXVF5QN0X2VYCD81HMN"
npm http request GET https://registry.npmjs.org/isarray
npm http 304 https://registry.npmjs.org/isarray
npm verb etag https://registry.npmjs.org/isarray from cache
npm verb get saving isarray to /Users/omarpadilla/.npm/registry.npmjs.org/isarray/.cache.json
npm verb afterAdd /Users/omarpadilla/.npm/isarray/0.0.1/package/package.json not in flight; writing
npm verb afterAdd /Users/omarpadilla/.npm/isarray/0.0.1/package/package.json written

It's been stuck there for over 10 minutes.   Any suggestions?

**Comment by opadillaintegrify** [comment]
I just kept executing npm install -g strongloop --verbose over and over again.  Each time it got deeper and deeper.  Eventually after about 5-10 tries the whole thing completed.

**Comment by sam-github** [comment]
@opadillaintegrify, sorry this didn't work for you, but like I told the OP, npm hanging while attempting to download a module from its registry is an npm bug, you should report at https://github.com/npm/npm.

**Comment by sam-github** [comment]
Either that, or chalk it up to network performance, and check your router.

**Comment by ShashankDesai** [comment]
Same here. I'm stuck at 
npm verb get https://registry.npmjs.org/loopback not expired, no request
npm verb addNamed "2.25.0" is a plain semver version for loopback
npm verb afterAdd /home/shashank/.npm/loopback/2.25.0/package/package.json not in flight; writing
npm verb afterAdd /home/shashank/.npm/loopback/2.25.0/package/package.json written
loadDep:sl-blip -> networ \ |#######################-----------------------------------------------------

**Comment by rmg** [comment]
@ShashankDesai are you behind a firewall or proxy that blocks access to some hosts? If so, that would slow things down considerably while npm waits for certain requests to timeout.

**Comment by ShashankDesai** [comment]
Hey it worked... That was a lot of dependencies to install.
I cleared npm cache though.

**Comment by rmg** [comment]
I'm going to close this since most of the conversation seems to be unrelated to the original issue.

@RV2013 please re-open if you are still having the problem originally described.
