### ISSUE TITLE
Failed to install strongloop

### ISSUE THREAD

**Issue by developersencha** [strongloop/strongloop#207]
I am trying to install strongloop (npm install -g strongloop) in windows 8.1 with node.js 0.10.33 (I have tried also with 0.12.2), python 2.7 is installed but I take the following error:

> sqlite3@3.0.5 install C:\Users\Nik\AppData\Roaming\npm\node_modules\strongloo
p\node_modules\strong-arc\node_modules\strong-mesh-client\node_modules\strong-pm
\node_modules\strong-mesh-models\node_modules\minkelite\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Command failed:
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: The filename or extension is too long.

C:\Users\Nik\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-ar
c\node_modules\strong-mesh-client\node_modules\strong-pm\node_modules\strong-mes
h-models\node_modules\minkelite\node_modules\sqlite3\lib\binding\node-v11-win32-
x64\node_sqlite3.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at [eval]:1:1
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:536:25)
    at startup (node.js:80:7)
    at node.js:906:3

node-pre-gyp ERR! Testing pre-built binary failed, attempting to source compile

C:\Users\Nik\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-ar
c\node_modules\strong-mesh-client\node_modules\strong-pm\node_modules\strong-mes
h-models\node_modules\minkelite\node_modules\sqlite3>node "C:\Program Files\node
js\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.j
s" rebuild --name=sqlite3 --configuration=Release --module_name=node_sqlite3 --v
ersion=3.0.5 --major=3 --patch=5 --runtime=node --node_abi=node-v11 --platform=w
in32 --target_platform=win32 --arch=x64 --target_arch=x64 --module_main=./lib/sq
lite3 --host=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=C:\Users
\Nik\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-arc\node_m
odules\strong-mesh-client\node_modules\strong-pm\node_modules\strong-mesh-models
\node_modules\minkelite\node_modules\sqlite3\lib\binding\node-v11-win32-x64 --mo
dule=C:\Users\Nik\AppData\Roaming\npm\node_modules\strongloop\node_modules\stro
ng-arc\node_modules\strong-mesh-client\node_modules\strong-pm\node_modules\stron
g-mesh-models\node_modules\minkelite\node_modules\sqlite3\lib\binding\node-v11-w
in32-x64\node_sqlite3.node --remote_path=./sqlite3/v3.0.5/ --package_name=node-v
11-win32-x64.tar.gz --staged_tarball=build\stage\sqlite3\v3.0.5\node-v11-win32-x
64.tar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0
.5/ --hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.5/
node-v11-win32-x64.tar.gz --msvs_version=2013
Warning: Missing input files:
C:\Users\Nik\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-ar
c\node_modules\strong-mesh-client\node_modules\strong-pm\node_modules\strong-mes
h-models\node_modules\minkelite\node_modules\sqlite3\build\deps\..\..\deps\sqlit
e-autoconf-3080701.tar.gz
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets
(4832,39): error MSB4023: Cannot evaluate the item metadata "%(FullPath)". The
item metadata "%(FullPath)" cannot be applied to the path "Release\obj\action_b
efore_build\action_before_build.exe". C:\Users\Nik\AppData\Roaming\npm\node_mo
dules\strongloop\node_modules\strong-arc\node_modules\strong-mesh-client\node_m
odules\strong-pm\node_modules\strong-mesh-models\node_modules\minkelite\node_mo
dules\sqlite3\build\deps\Release\obj\action_before_build\action_before_build.ex
e [C:\Users\Nik\AppData\Roaming\npm\node_modules\strongloop\node_modules\stron
g-arc\node_modules\strong-mesh-client\node_modules\strong-pm\node_modules\stron
g-mesh-models\node_modules\minkelite\node_modules\sqlite3\build\deps\action_bef
ore_build.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:
12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild" "--name=sqlite3" "--configuration=Rel
ease" "--module_name=node_sqlite3" "--version=3.0.5" "--major=3" "--patch=5" "--
runtime=node" "--node_abi=node-v11" "--platform=win32" "--target_platform=win32"
 "--arch=x64" "--target_arch=x64" "--module_main=./lib/sqlite3" "--host=https://
mapbox-node-binary.s3.amazonaws.com/" "--module_path=C:\\Users\\Nik\\AppData\\R
oaming\\npm\\node_modules\\strongloop\\node_modules\\strong-arc\\node_modules\\s
trong-mesh-client\\node_modules\\strong-pm\\node_modules\\strong-mesh-models\\no
de_modules\\minkelite\\node_modules\\sqlite3\\lib\\binding\\node-v11-win32-x64"
"--module=C:\\Users\\Nik\\AppData\\Roaming\\npm\\node_modules\\strongloop\\node
_modules\\strong-arc\\node_modules\\strong-mesh-client\\node_modules\\strong-pm\
\node_modules\\strong-mesh-models\\node_modules\\minkelite\\node_modules\\sqlite
3\\lib\\binding\\node-v11-win32-x64\\node_sqlite3.node" "--remote_path=./sqlite3
/v3.0.5/" "--package_name=node-v11-win32-x64.tar.gz" "--staged_tarball=build\\st
age\\sqlite3\\v3.0.5\\node-v11-win32-x64.tar.gz" "--hosted_path=https://mapbox-n
ode-binary.s3.amazonaws.com/sqlite3/v3.0.5/" "--hosted_tarball=https://mapbox-no
de-binary.s3.amazonaws.com/sqlite3/v3.0.5/node-v11-win32-x64.tar.gz" "--msvs_ver
sion=2013"
gyp ERR! cwd C:\Users\Nik\AppData\Roaming\npm\node_modules\strongloop\node_modu
les\strong-arc\node_modules\strong-mesh-client\node_modules\strong-pm\node_modul
es\strong-mesh-models\node_modules\minkelite\node_modules\sqlite3
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd rebuild --name=sq
lite3 --configuration=Release --module_name=node_sqlite3 --version=3.0.5 --major
=3 --patch=5 --runtime=node --node_abi=node-v11 --platform=win32 --target_platfo
rm=win32 --arch=x64 --target_arch=x64 --module_main=./lib/sqlite3 --host=https:/
/mapbox-node-binary.s3.amazonaws.com/ --module_path=C:\Users\Nik\AppData\Roamin
g\npm\node_modules\strongloop\node_modules\strong-arc\node_modules\strong-mesh-c
lient\node_modules\strong-pm\node_modules\strong-mesh-models\node_modules\minkel
ite\node_modules\sqlite3\lib\binding\node-v11-win32-x64 --module=C:\Users\Nik\A
ppData\Roaming\npm\node_modules\strongloop\node_modules\strong-arc\node_modules\
strong-mesh-client\node_modules\strong-pm\node_modules\strong-mesh-models\node_m
odules\minkelite\node_modules\sqlite3\lib\binding\node-v11-win32-x64\node_sqlite
3.node --remote_path=./sqlite3/v3.0.5/ --package_name=node-v11-win32-x64.tar.gz
--staged_tarball=build\stage\sqlite3\v3.0.5\node-v11-win32-x64.tar.gz --hosted_p
ath=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.5/ --hosted_tarball
=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.5/node-v11-win32-x64.t
ar.gz --msvs_version=2013' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Nik\AppData\R
oaming\npm\node_modules\strongloop\node_modules\strong-arc\node_modules\strong-m
esh-client\node_modules\strong-pm\node_modules\strong-mesh-models\node_modules\m
inkelite\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:71:2
9)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:756:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_proces
s.js:823:5)
node-pre-gyp ERR! System Windows_NT 6.2.9200
node-pre-gyp ERR! command "node" "C:\\Users\\Nik\\AppData\\Roaming\\npm\\node_m
odules\\strongloop\\node_modules\\strong-arc\\node_modules\\strong-mesh-client\\
node_modules\\strong-pm\\node_modules\\strong-mesh-models\\node_modules\\minkeli
te\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "insta
ll" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Nik\AppData\Roaming\npm\node_modules\strongloop\
node_modules\strong-arc\node_modules\strong-mesh-client\node_modules\strong-pm\n
ode_modules\strong-mesh-models\node_modules\minkelite\node_modules\sqlite3
node-pre-gyp ERR! node -v v0.10.33
node-pre-gyp ERR! node-pre-gyp -v v0.6.2
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd rebuild --name=sqlite3 --configuration=Release -
-module_name=node_sqlite3 --version=3.0.5 --major=3 --patch=5 --runtime=node --n
ode_abi=node-v11 --platform=win32 --target_platform=win32 --arch=x64 --target_ar
ch=x64 --module_main=./lib/sqlite3 --host=https://mapbox-node-binary.s3.amazonaw
s.com/ --module_path=C:\Users\Nik\AppData\Roaming\npm\node_modules\strongloop\n
ode_modules\strong-arc\node_modules\strong-mesh-client\node_modules\strong-pm\no
de_modules\strong-mesh-models\node_modules\minkelite\node_modules\sqlite3\lib\bi
nding\node-v11-win32-x64 --module=C:\Users\Nik\AppData\Roaming\npm\node_modules
\strongloop\node_modules\strong-arc\node_modules\strong-mesh-client\node_modules
\strong-pm\node_modules\strong-mesh-models\node_modules\minkelite\node_modules\s
qlite3\lib\binding\node-v11-win32-x64\node_sqlite3.node --remote_path=./sqlite3/
v3.0.5/ --package_name=node-v11-win32-x64.tar.gz --staged_tarball=build\stage\sq
lite3\v3.0.5\node-v11-win32-x64.tar.gz --hosted_path=https://mapbox-node-binary.
s3.amazonaws.com/sqlite3/v3.0.5/ --hosted_tarball=https://mapbox-node-binary.s3.
amazonaws.com/sqlite3/v3.0.5/node-v11-win32-x64.tar.gz --msvs_version=2013' (1)

npm ERR! sqlite3@3.0.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.0.5 install script.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "strongloop" "--msvs_ver
sion=2013"
npm ERR! cwd C:\Users\Nik
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by kraman** [comment]
Hi @developersencha The package causing this failure has been reverted to an older version. Please try your installation again.

**Comment by developersencha** [comment]
All OK thank you very much.

**Comment by sam-github** [comment]
@kraman is that correct `strong-mesh-client\node_modules\strong-pm`: arc depends on mesh-client, which depends on strong-pm? It looks like the error might be related to path depths... we might need to require npm3, or else need to pull some deps up to the top-level, so they don't get installed multiple times deep in the tree.

**Comment by rmg** [comment]
It looks like strong-mesh-client depends on strong-pm to get access to its client, which is actually in strong-mesh-models, which it already depends on.

**Comment by kraman** [comment]
Yah, its pretty deep.

```
strong-arc --> strong-mesh-client --> strong-pm --> strong-mesh-models --> minkelite --> node-sqlite3
```

perhaps `strongloop` can depend on node-sqlite3 directly to reduce the depth at which it is installed?

But depending on where someone installs node, the path could still be long ... eg above `C:\Users\Nik\AppData\Roaming\npm\node_modules\` already adds a bunch of depth.

**Comment by rmg** [comment]
There's also no guarantee that with that strategy npm won't install multiple copies of node-sqlite3 anyway. :-(

**Comment by kraman** [comment]
@rmg doesnt it just do a version match to figure out if a new copy is required. We *should* only need to make sure the npm version selectors match in both places.

**Comment by rmg** [comment]
That behaviour is dependant on the order the dependencies are installed, which I believe is currently dependant on which ones download/install first. A future version of npm will resolve the entire tree before installing anything, which will solve _a lot_ of these Windows path depth problems.

**Comment by Setogit** [comment]
added an update to https://github.com/strongloop-internal/scrum-nodeops/issues/423.
