### ISSUE TITLE
Update your URL

### ISSUE THREAD

**Issue by FrankHassanabad** [strongloop/strongloop#208]
At the front of your project it has this as the cli's url:
strongloop controller CLI http://docs.strongloop.com/display/SLC/StrongLoop+Controller

However, that confluence page changed and that no longer points to anything useful.

Perhaps here? http://docs.strongloop.com/display/SLC/Running+apps+with+slc

**Comment by crandmck** [comment]
Fixed.  Thanks for reporting.
