### ISSUE TITLE
Error while installing strongloopr. Win 7 x64.

### ISSUE THREAD

**Issue by loxovaz** [strongloop/strongloop#210]
> strong-agent@1.4.0 install C:\Users\username\AppData\Roaming\npm\node_modules\
strongloop\node_modules\strong-agent
> node-gyp rebuild || exit 0

C:\Users\username\AppData\Roaming\npm\node_modules\strongloop\node_modules\stron
g-agent>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\n
ode_modules\node-gyp\bin\node-gyp.js" rebuild
child_process: customFds option is deprecated, use stdio instead.
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppBuild.targets(29
7,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.
  TargetFrameworkVersion or PlatformToolset may be set to an invalid version nu
mber. [C:\Users\username\AppData\Roaming\npm\node_modules\strongloop\node_modul
es\strong-agent\build\strong-agent.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\x64\Microsoft.Cpp.x
64.targets(146,5): error MSB6006: "CL.exe" exited with code -1073741515. [C:\Us
ers\username\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-ag
ent\build\strong-agent.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067
:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\username\AppData\Roaming\npm\node_modules\strongloop\node_
modules\strong-agent
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm WARN optional dep failed, continuing heapdump@0.2.10

**Comment by rmg** [comment]
@piscisaureus @bnoordhuis are either of you able to decipher this VCC build error?

**Comment by bnoordhuis** [comment]
It's probably [this gyp issue](https://code.google.com/p/gyp/issues/detail?id=457).  In a nutshell, gyp detects the wrong toolchain.  Running the command below from the shell before running npm again should fix it.

```
call "C:\Program Files\Microsoft SDKs\Windows\v7.1\bin\Setenv.cmd" /Release /x86
```

Replace `/x86` with `/x64` for 64 bits builds.

**Comment by loxovaz** [comment]
gyp is a nightmare. It's my third x64 PC configuration and every time it needs for some tricks
Thanks a lot guys! It's solved
