### ISSUE TITLE
`slc update` should only update when new dependencies are available

### ISSUE THREAD

**Issue by superkhau** [strongloop/strongloop#211]
`slc update` should take a snapshot of the current version of dependencies installed, get a list of remote item versions, diff them, and update if necessary. At the moment, it always updates even if the dependencies are identical.

**Comment by rmg** [comment]
As of this writing, `npm install -g strongloop` installs 3297 packages.. not sure doing those version checks is going to be much better.

**Comment by superkhau** [comment]
That is a lot. Closing this issue as it seems like a futile battle. ;)

**Comment by sam-github** [comment]
Unfortunately, we'd have to basically re-invent npm's install, but "better". Its a hard problem, lets let npm face it.

**Comment by chandadharap** [comment]
agreed.
