### ISSUE TITLE
`slc loopback` complains missing dependency after upgrade strongloop to 3.1

### ISSUE THREAD

**Issue by clarkorz** [strongloop/strongloop#214]
```
$ slc loopback
Error loading module "loopback":
 [Error: The middleware loopback.cookieParser is not installed.
Run `npm install --save cookie-parser` to fix the problem.]
```

**Comment by rmg** [comment]
@clarkorz did you find a solution?

**Comment by clarkorz** [comment]
false alarm. I install a global loopback accidentally

**Comment by clarkorz** [comment]
I just found that I install a global loopback module accidentally. But after remove global loopback and strongloop module, then install strongloop again, the problem is still there.

More worse, all generator commands complains this message.

**Comment by rmg** [comment]
I'll try to get a fix out shortly.

**Comment by clarkorz** [comment]
@rmg I'm using node 0.12 with npm 2.7.4

It seems that `cookie-parser` module hasn't been installed by npm, which should be. Weird.

**Comment by rmg** [comment]
Ya, it has to do with where the middleware is installed relative to where loopback is installed. I've got a fix I'm about to PR.

**Comment by rmg** [comment]
Published strongloop@3.1.1 with the fix.

**Comment by rmg** [comment]
@clarkorz let me know if 3.1.1 works better for you.

**Comment by clarkorz** [comment]
@rmg Yes, it works now~ thx
