### ISSUE TITLE
slc debug should invoke node-inspector that has biased-opener

### ISSUE THREAD

**Issue by srguiwiz** [strongloop/strongloop#218]
Recent versions of `node-inspector` use `biased-opener` since [ea1b24c](https://github.com/node-inspector/node-inspector/commit/ea1b24c517bc05464a9ebe9055cf498cb4eca77d).

Which means from `node-debug` if present a fitting browser (e.g. Chrome) will launch with the debugger UI, even if another browser is set as system default,

Would be nice if `slc debug` also would open a fitting browser, even if another browser is set as system default.

**Comment by sam-github** [comment]
When `slc debug` (which is just a facade around node-debug from node-inspector) is updated to the latest node-inspector, it will do this. In the meantime, we recommend using node-debug.

/cc @altsang @bajtos

**Comment by rmg** [comment]
This issue is quite old and debugging of node apps has changed dramatically since this was opened, including a standalone `node-inspect` CLI maintained by the Node.js foundation: https://github.com/nodejs/node-inspect
