### ISSUE TITLE
Please fix the issue with npm install -g strongloop

### ISSUE THREAD

**Issue by ynagarjuna1995** [strongloop/strongloop#223]
### Error along with solution which I have tried are mentioned below please try to fix the issue asap 

Hey 

### Error goes like this ..

vagrant@strongloop:~$ sudo  npm install -g strongloop
npm WARN deprecated json-file-plus@2.0.0: Before v3.0.0, errors in fs.writeFile
would not be propagated

> heapdump@0.3.5 install /usr/local/lib/node_modules/strongloop/node_modules/str
ong-supervisor/node_modules/heapdump
> node-gyp rebuild

make: Entering directory `/usr/local/lib/node_modules/strongloop/node_modules/st
rong-supervisor/node_modules/heapdump/build'
  CXX(target) Release/obj.target/addon/src/heapdump.o
  SOLINK_MODULE(target) Release/obj.target/addon.node
  SOLINK_MODULE(target) Release/obj.target/addon.node: Finished
  COPY Release/addon.node
make: Leaving directory `/usr/local/lib/node_modules/strongloop/node_modules/str
ong-supervisor/node_modules/heapdump/build'

> strong-fork-syslog@1.2.3 install /usr/local/lib/node_modules/strongloop/node_m
odules/strong-supervisor/node_modules/strong-fork-syslog
> node-gyp rebuild

make: Entering directory `/usr/local/lib/node_modules/strongloop/node_modules/st
rong-supervisor/node_modules/strong-fork-syslog/build'
  CXX(target) Release/obj.target/syslog/syslog.o
  SOLINK_MODULE(target) Release/obj.target/syslog.node
  SOLINK_MODULE(target) Release/obj.target/syslog.node: Finished
  COPY Release/syslog.node
make: Leaving directory `/usr/local/lib/node_modules/strongloop/node_modules/str
ong-supervisor/node_modules/strong-fork-syslog/build'
npm WARN deprecated json-file-plus@1.0.7: Before v3.0.0, errors in fs.writeFile
would not be propagated

> strong-agent@1.5.1 install /usr/local/lib/node_modules/strongloop/node_modules
/strong-agent
> node-gyp rebuild || exit 0

make: Entering directory `/usr/local/lib/node_modules/strongloop/node_modules/st
rong-agent/build'
  CXX(target) Release/obj.target/strong-agent/src/strong-agent.o
In file included from ../src/strong-agent.cc:15:0:
../src/watchdog.h: In function ‘void strongloop::agent::watchdog::PatchSyscall()
’:
../src/watchdog.h:169:52: warning: dereferencing type-punned pointer will break
strict-aliasing rules [-Wstrict-aliasing]
../src/watchdog.h:198:52: warning: dereferencing type-punned pointer will break
strict-aliasing rules [-Wstrict-aliasing]
../src/watchdog.h:199:75: warning: dereferencing type-punned pointer will break
strict-aliasing rules [-Wstrict-aliasing]
  SOLINK_MODULE(target) Release/obj.target/strong-agent.node
  SOLINK_MODULE(target) Release/obj.target/strong-agent.node: Finished
  COPY Release/strong-agent.node
make: Leaving directory `/usr/local/lib/node_modules/strongloop/node_modules/str
ong-agent/build'
npm WARN optional dep failed, continuing loopback@2.17.2

> ws@0.4.32 install /usr/local/lib/node_modules/strongloop/node_modules/node-ins
pector/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

## Try the below steps to fix the issue

So please try to install node-gyp and json-file-plus using below commands

    sudo npm install -g node-gyp

    sudo npm install -g json-file-plus@3.0.0

I had the same issue with node v0.12.0, v0.12.1, npm v2.5.1 and operating system (Ubuntu 12.04.5 and 14.04 )Installation seems to hang but if you press enter couple of times its responsive again and you get into the shell.

After that you will notice that for some reason symbolic links are not being created but the module seems to be installed correctly.(Even if you don't get any output please try the below steps )
My error on my system :

  To fix this I have created the sym links manually like this:

    sudo ln -s /usr/local/lib/node_modules/strongloop/bin/slc /usr/local/bin/

This will enable you to use slc cli across the machine. Also, if you are using loopback-sdk-angular-cli which containes lb-ng and lb-ng-doc commands (which should be installed with npm install -g strongloop) you need to create those symlinks aswell. You do that like this:

    sudo ln -s /usr/local/lib/node_modules/strongloop/node_modules/loopback-sdk-angular-cli/bin/* /usr/local/bin/

This will enable you to use lb-ng across the machine, however it could happen as well that the tool will be broken with missing dependency errors. To fix those, enter to the path where module installed and execute npm install to install dependencies. On ubuntu 14.04 LTS you do that like this:

    cd /usr/local/lib/node_modules/strongloop/node_modules/loopback-sdk-angular-cli

    npm install

**Comment by ynagarjuna1995** [comment]
## Unable to work with loopback after symlinking

   slc loopback 
 not working

#### Please check the error below

vagrant@strongloop:~$ slc --version
strongloop v4.0.1 (node v0.12.2)
├── strong-arc@1.2.1
├── strong-build@2.0.0 (0cb88da)
├── strong-deploy@2.2.0 (ada97d4)
├── strong-pm@4.1.0 (4629260)
├── strong-registry@1.1.4 (aab3dbb)
├── strong-start@1.1.0 (04195e6)
├─┬ strong-supervisor@1.6.0 (baa3fcd)
│ └── strong-agent@1.5.1
├── generator-loopback@1.9.1
├── node-inspector@0.7.4
└── nodefly-register@0.3.3

vagrant@strongloop:~$ slc loopback:example
Error loading module "loopback":
 { [Error: Cannot find module 'yeoman-generator'] code: 'MODULE_NOT_FOUND' }
vagrant@strongloop:~$ sudo ln -s /usr/local/lib/node_modules/strongloop/node_mo
dules/loopback/bin/* /usr/local/bin/
ln: failed to create symbolic link `/usr/local/bin/*': File exists

**Comment by rmg** [comment]
@ynagarjuna1995 what is the actual error you were trying to fix by manually symlinking files? The log messages you pasted show only warnings, not fatal errors. Also, you do not need to install `node-gyp` because a version of it is already bundled with `npm`.

What are you using as a base box for your vagrant VM?

**Comment by rmg** [comment]
If you are using VirtualBox for Vagrant, you could try the [strongloop/node-trusty](https://atlas.hashicorp.com/strongloop/boxes/node-trusty) box, which was just updated to include strongloop@4.0.2.

**Comment by dtt101** [comment]
I get similar errors on Ubuntu 14.04 after running ```npm install -g strongloop```

```
> utf-8-validate@1.1.0 install /home/dtt101/.nvm/versions/node/v0.12.7/lib/node_modules/strongloop/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory `/home/dtt101/.nvm/versions/node/v0.12.7/lib/node_modules/strongloop/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory `/home/dtt101/.nvm/versions/node/v0.12.7/lib/node_modules/strongloop/node_modules/ws/node_modules/utf-8-validate/build'
 
> bufferutil@1.1.0 install /home/dtt101/.nvm/versions/node/v0.12.7/lib/node_modules/strongloop/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory `/home/dtt101/.nvm/versions/node/v0.12.7/lib/node_modules/strongloop/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
make: Leaving directory `/home/dtt101/.nvm/versions/node/v0.12.7/lib/node_modules/strongloop/node_modules/ws/node_modules/bufferutil/build'
 
> heapdump@0.3.6 install /home/dtt101/.nvm/versions/node/v0.12.7/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/heapdump
> node-gyp rebuild

make: Entering directory `/home/dtt101/.nvm/versions/node/v0.12.7/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/heapdump/build'
  CXX(target) Release/obj.target/addon/src/heapdump.o
  SOLINK_MODULE(target) Release/obj.target/addon.node
  COPY Release/addon.node
make: Leaving directory `/home/dtt101/.nvm/versions/node/v0.12.7/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/heapdump/build'
 
> strong-fork-syslog@1.2.3 install /home/dtt101/.nvm/versions/node/v0.12.7/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-fork-syslog
> node-gyp rebuild

make: Entering directory `/home/dtt101/.nvm/versions/node/v0.12.7/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-fork-syslog/build'
  CXX(target) Release/obj.target/syslog/syslog.o
  SOLINK_MODULE(target) Release/obj.target/syslog.node
  COPY Release/syslog.node
make: Leaving directory `/home/dtt101/.nvm/versions/node/v0.12.7/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-fork-syslog/build'
npm WARN deprecated MD5@1.2.2: deprecated, use lowercase 'md5@2.x' from now on
 
> strong-agent@1.6.3 install /home/dtt101/.nvm/versions/node/v0.12.7/lib/node_modules/strongloop/node_modules/strong-agent
> node-gyp rebuild || exit 0

make: Entering directory `/home/dtt101/.nvm/versions/node/v0.12.7/lib/node_modules/strongloop/node_modules/strong-agent/build'
  CXX(target) Release/obj.target/strong-agent/src/strong-agent.o
  SOLINK_MODULE(target) Release/obj.target/strong-agent.node
  COPY Release/strong-agent.node
make: Leaving directory `/home/dtt101/.nvm/versions/node/v0.12.7/lib/node_modules/strongloop/node_modules/strong-agent/build'
 
> ws@0.4.32 install /home/dtt101/.nvm/versions/node/v0.12.7/lib/node_modules/strongloop/node_modules/strong-pm/node_modules/express-ws/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/dtt101/.nvm/versions/node/v0.12.7/lib/node_modules/strongloop/node_modules/strong-pm/node_modules/express-ws/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory `/home/dtt101/.nvm/versions/node/v0.12.7/lib/node_modules/strongloop/node_modules/strong-pm/node_modules/express-ws/node_modules/ws/build'
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
\
> ws@0.4.32 install /home/dtt101/.nvm/versions/node/v0.12.7/lib/node_modules/strongloop/node_modules/node-inspector/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


zsh: killed     npm install -g strongloop
```
I am using:

 * nvm 0.25.4
 * npm 2.11.3
 * node 0.12.7 (I have also tried with 0.10)
 * Ubuntu 14.04

When I list my globally installed packages with (```npm list -g --depth=0```) I can see ```strongloop@4.0.5``` but the slc command is unavailable (I get zsh: command not found: slc).

**Comment by rmg** [comment]
@ynagarjuna1995 re-open if you still need help with this.
