### ISSUE TITLE
How get the postdata in a custom Express route with strongloop ?

### ISSUE THREAD

**Issue by PanYuntao** [strongloop/strongloop#224]
How get the post data In a custom Express route with strongloop .
like this don't get postdata
```
module.exports = function(app) {
    var router = app.loopback.Router();
    router.post('/ping', function(req, res) {
        console.log(req.body);
        res.send('pongaroo');
    });
    app.use(router);
};
```

**Comment by rmg** [comment]
@PanYuntao you need to make sure that any body parsing middleware you are using is added before your `/ping` route is added.

Can you post this on stackoverflow.com or the [loopback mailing list](https://groups.google.com/forum/#!forum/loopbackjs)?

**Comment by PanYuntao** [comment]
@rmg  Thanks for your help.
