### ISSUE TITLE
Failed to install strongloop 4.0.1 (windows, 260 chars path length limit)

### ISSUE THREAD

**Issue by javefang** [strongloop/strongloop#225]
I'm working on a windows machine, the installation fails when trying to compile one of the dependency library due to the windows 260 characters path length limit. Is there a way to work around this?

$ npm install -g strongloop
...
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(399,5): error MSB319
1: Unable to create directory "Release\obj\action_before_build\action_b.BF299DDE.tlog\". The specified
 path, file name, or both are too long. The fully qualified file name must be less than 260 characters
, and the directory name must be less than 248 characters. [C:\Users\x.fang\AppData\Roaming\npm\node_m
odules\strongloop\node_modules\strong-arc\node_modules\strong-pm\node_modules\strong-mesh-models\node_
modules\minkelite\node_modules\sqlite3\build\deps\action_before_build.vcxproj]

**Comment by rmg** [comment]
@javefang I just published 4.0.2 with a fix, can you give it a try? You may need to `npm cache clear` first to make sure npm pulls down the latest.

**Comment by javefang** [comment]
It works now! Thanks for the amazingly fast fix :)

**Comment by rmg** [comment]
Glad to hear it :-)
