### ISSUE TITLE
'slc build' hangs

### ISSUE THREAD

**Issue by javefang** [strongloop/strongloop#227]
OS: windows 7
Node: 0.12.2
Strongloop: 4.0.2

The build script in my package.json is defined to run a gulp task ("gulp build-all"). It seems to hang when I build a .tgz package. Is there anyway I can debug this? Thanks in advance!

Below is the console output:
------------------
```
$ slc build --npm --scripts
Running `npm install`
Running `npm run build`
```

When I run "gulp build-all" directly from the same folder:
-------------------
```
$ gulp build-all
[15:27:57] Using gulpfile e:\git\btweb-staffhandbook\gulpfile.js
[15:27:57] Starting 'lb-services'...
[15:27:57] Starting 'html'...
[15:27:57] Finished 'html' after 13 ms
[15:27:57] Starting 'js'...
[15:27:57] Starting 'sass'...
[15:27:57] Starting 'css-thirdparty'...
[15:27:57] Finished 'css-thirdparty' after 5.28 ms
[15:27:57] Starting 'assets'...
[15:27:57] Finished 'assets' after 3.55 ms
[15:27:58] Finished 'sass' after 613 ms
Loading LoopBack app "e:\\git\\<app_name_removed>\\server\\server.js"
Generating "lbServices" for the API endpoint "/api"
Warning: scope user.identities targets class "userIdentity", which is not exposed
via remoting. The Angular code for this scope won't be generated.
Warning: scope user.credentials targets class "userCredential", which is not exposed
via remoting. The Angular code for this scope won't be generated.
Warning: scope user.accessTokens targets class "accessToken", which is not exposed
via remoting. The Angular code for this scope won't be generated.
Saving the generated services source to "e:\\git\\<app_name_removed>\\client\\src\\app\\common\\services\\lb-services.js"
[15:28:02] Finished 'lb-services' after 5.11 s
[15:28:02] Finished 'js' after 5.1 s
[15:28:02] Starting 'build-client'...
[15:28:02] Finished 'build-client' after 11 μs
[15:28:02] Starting 'build-all'...
[15:28:02] Finished 'build-all' after 16 μs
```

-----------------
Below is the package.json
```json
{
  "name": "<app_name_removed>",
  "version": "1.0.0",
  "main": "server/server.js",
  "scripts": {
    "pretest": "jshint .",
    "test-all": "npm run test && npm run test-integration",
    "test": "mocha --reporter spec test",
    "test-integration": "mocha --reporter spec test-integration",
    "postinstall": "bower install",
    "build": "gulp build-all",
    "start": "slc run"
  },
  "dependencies": {
    "angular": "^1.3.15",
    "angular-bootstrap": "^0.12.0",
    "angular-filter": "^0.5.4",
    "angular-moment": "^0.9.2",
    "angular-resource": "^1.3.15",
    "angular-ui-router": "^0.2.13",
    "async": "^0.9.0",
    "body-parser": "^1.12.3",
    "bootstrap-sass": "^3.3.4",
    "compression": "^1.0.3",
    "connect-ensure-login": "^0.1.1",
    "cookie-parser": "^1.3.4",
    "debug": "^2.1.3",
    "errorhandler": "^1.1.1",
    "express-session": "^1.11.1",
    "ldapjs": "^0.7.1",
    "lodash": "^3.5.0",
    "loopback": "^2.8.0",
    "loopback-boot": "^2.6.5",
    "loopback-component-passport": "^1.3.0",
    "loopback-connector-mongodb": "^1.8.0",
    "loopback-connector-rest": "^1.7.0",
    "loopback-datasource-juggler": "^2.7.0",
    "moment": "^2.10.2",
    "serve-favicon": "^2.0.1"
  },
  "optionalDependencies": {
    "loopback-explorer": "^1.1.0"
  },
  "devDependencies": {
    "browserify": "^9.0.3",
    "browserify-shim": "^3.8.3",
    "gulp": "^3.8.11",
    "gulp-concat": "^2.5.2",
    "gulp-rename": "^1.2.0",
    "gulp-sass": "^1.3.3",
    "gulp-shell": "^0.4.0",
    "gulp-sourcemaps": "^1.5.1",
    "jshint": "^2.5.6",
    "mocha": "^2.2.1",
    "should": "^5.2.0",
    "vinyl-buffer": "^1.0.0",
    "vinyl-source-stream": "^1.1.0"
  },
  "browser": {},
  "browserify-shim": {},
  "repository": {
    "type": "",
    "url": ""
  },
  "description": "<app_name_removed>",
  "bundleDependencies": [
    "angular",
    "angular-bootstrap",
    "angular-filter",
    "angular-moment",
    "angular-resource",
    "angular-ui-router",
    "async",
    "body-parser",
    "bootstrap-sass",
    "compression",
    "connect-ensure-login",
    "cookie-parser",
    "debug",
    "errorhandler",
    "express-session",
    "ldapjs",
    "lodash",
    "loopback",
    "loopback-boot",
    "loopback-component-passport",
    "loopback-connector-mongodb",
    "loopback-connector-rest",
    "loopback-datasource-juggler",
    "loopback-explorer",
    "moment",
    "serve-favicon"
  ]
}
```

**Comment by javefang** [comment]
Sorry guys, seems like a problem with the 'gulp-shell' module I'm using inside one of my gulp task

var shell = require('gulp-shell');
gulp.task('lb-services', shell.task(['lb-ng ./server/server.js client/src/app/common/services/lb-services.js']));

removing this task seems to have fixed the issue.

**Comment by rmg** [comment]
Does `npm run build` work when you run it yourself with that gulp-shell task still enabled?

**Comment by javefang** [comment]
Yep it works when I call "gulp lb-services" directly.

**Comment by rmg** [comment]
@javefang but does it work when you call `npm run build`? That is how `slc build` invokes it.

**Comment by javefang** [comment]
Yes it works when calling `npm run build`, I'll will paste the tests below

**Comment by javefang** [comment]
I have started a new loopback project.

package.json
-------------
{
  "name": "sl-build-test",
  "version": "1.0.0",
  "main": "server/server.js",
  "scripts": {
    "pretest": "jshint .",
    "build": "gulp <task>"
  },
  "dependencies": {
    "compression": "^1.0.3",
    "cors": "^2.5.2",
    "errorhandler": "^1.1.1",
    "loopback": "^2.14.0",
    "loopback-boot": "^2.6.5",
    "loopback-datasource-juggler": "^2.19.0",
    "serve-favicon": "^2.0.1"
  },
  "optionalDependencies": {
    "loopback-explorer": "^1.1.0"
  },
  "devDependencies": {
    "gulp": "^3.8.11",
    "gulp-concat": "^2.5.2",
    "gulp-shell": "^0.4.1",
    "jshint": "^2.5.6"
  },
  "repository": {
    "type": "",
    "url": ""
  },
  "description": "sl-build-test",
  "bundleDependencies": [
    "compression",
    "cors",
    "errorhandler",
    "loopback",
    "loopback-boot",
    "loopback-datasource-juggler",
    "loopback-explorer",
    "serve-favicon"
  ]
}



gulpfile.js
-------------
'use strict';

var gulp = require('gulp');
var shell = require('gulp-shell');

gulp.task('foo', shell.task([
  'lb-ng server/server.js client/lb-services.js'
]));

gulp.task('bar', function () {
  return gulp.src('./client/lib/*.js')
    .pipe(concat('app.js'))
    .pipe(gulp.dest('./client/dist/'));
});

gulp.task('empty', function () {
  console.log('do nothing');
});




Console output when changing `<task>` in package.json to one of the following:

1.task: `empty` (empty task, do nothing, return nothing)
------------
$ slc build --npm
Running `npm install --ignore-scripts`
Running `npm run build`
Running `npm prune --production`
Running `npm --quiet pack`
Running `mv -f sl-build-test-1.0.0.tgz ../sl-build-test-1.0.0.tgz`

2.task: `foo` (task with `gulp-shell`)
----------
$ slc build --npm --scripts
Running `npm install`
Running `npm run build`
^C (cancelled manually after 30 secs)

3. task: `bar` (task with `gulp-concat`, return stream)
-----------
$ slc build --npm --scripts
Running `npm install`
Running `npm run build`
Running `npm prune --production`
Running `npm --quiet pack`
Running `mv -f sl-build-test-1.0.0.tgz ../sl-build-test-1.0.0.tgz`

**Comment by sam-github** [comment]
I believe there's an issue with gulp-shell where it doesn't work well when its spawned by node.

@rmg, do you recall where the issue where this was reported and tracked down?

**Comment by rmg** [comment]
@sam-github I don't recall a specific issue, but I just took a look and it seems likely that `lb-ng` is waiting for input, since gulp-shell seems to [make an effort to pipe it](https://github.com/sun-zheng-an/gulp-shell/blob/848cdf44c854b5e1c315f1a595810a7a0c2e89cc/index.js#L39-L72), but we don't do anything with it.

This also sounds similar to strongloop/gulp-loopback-sdk-angular#3

@javefang have you tried hitting `^D` when it hangs or doing `slc build --npm < /dev/null` to see if ending stdin lets it finish?

**Comment by sam-github** [comment]
If the stdin redirection is the problem, then we can redirect stdin from dev null when we spawn. Might be a good idea to do anyway.

**Comment by Setogit** [comment]
strong-build uses `shelljs` module to run commands.  The reported case uses `gulp-shell`, specifically `shell.task`.  Both `shelljs` and `gulp-shell` depend on `child-process.exec`.  There seems to be impedance mismatch between them.

Mitigation: use `shell.bind(null,`<commands array>) instead of `shell.task(`<commands array>).

https://github.com/Setogit/sky

In this example app, try comment/uncomment gulp.task('foo', ... ) and see what happens with `slc build --npm`:

- shell.task( ... ) will hang after `npm run build'
- shell.bind(null, ... ) will suceed.

**Comment by Setogit** [comment]
https://github.com/Setogit/sky

strong-build uses shelljs module to run commands. The reported case uses gulp-shell, specifically shell.task. Both shelljs and gulp-shell depend on child-process.exec. There seems to be impedance mismatch between them.

Mitigation: use shelljs.exec with [commands array].join(' && ') instead of gulpshell.task with [commands array]).

In this example app, compare foo and foo2 gulp tasks in package.json and see what happens with slc build --npm.

**Comment by sam-github** [comment]
@chandadharap this is a problem with underlying libraries (like gulp), doesn't seem fixable in strong-build, we should close as unfixable (but @Setogit points out some mitigations above).

**Comment by chandadharap** [comment]
well, then should we document mitigations? I'll close, but still needs an opnion. I have no strong one.
