### ISSUE TITLE
slc arc --> TypeError: undefined is not a function at C:\...\strong-mesh-client\proxy\boot\manager-host.js:43:16

### ISSUE THREAD

**Issue by Acaspita** [strongloop/strongloop#228]
After running slc arc in the folder of a loopback app, I get this: (Under Windows 8.1)
```
Loading workspace C:\Users\Acaspita\Documents\Projects\Loopback-App
Embedded Process Manager [(none)]:  starting
StrongLoop Arc is running here: http://localhost:4583/#/

C:\Users\Acaspita\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-arc\node_modules\strong-mesh-client\proxy\boot\manager-host.js:43
        return cb(err);
               ^
TypeError: undefined is not a function
    at C:\Users\Acaspita\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-arc\node_modules\strong-mesh-client\proxy\boot\manager-host.js:43:16
    at null._onTimeout (C:\Users\Acaspita\AppData\Roaming\npm\node_modules\strongloop\node_modules\loopback-datasource-juggler\lib\datasource.js:2036:7)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

**Comment by ritch** [comment]
This looks like a bug in the error handling code. Thanks for posting the issue (next time you can post to the strongloop/strong-arc repo if you'd like a quicker response).

I'll create a fix for the error handling code. If you would like to debug this before then you can modify that line of code mentioned in the error message to print the error

```js
console.log(err);
return cb ? cb(err) : null;
```

There is most likely some error during the process manager `sync` process. If you could post the error that would help us track it down (it might be something simple like file permissions).

**Comment by Acaspita** [comment]
Sure, I'll post it when I reach home. Thank you..

**Comment by Acaspita** [comment]
I tried to debug this issue on my machine with node-debug, but I'm not being able since I can't add the folder containing the code to workspace (bug?) and so I'm not able to put the break point on the that line.

**Comment by katherdx** [comment]
I am also getting same error.. any solution ?
