### ISSUE TITLE
Failed to create build products commit for `deploy`

### ISSUE THREAD

**Issue by carloscarcamo** [strongloop/strongloop#229]
Hello there, I have a problem when running:
```$ slc build```

This is the output:
```
Running `git branch "deploy"`
Not merging HEAD into `deploy`, already up to date.
Running `npm install --ignore-scripts`
Running `npm prune --production`
Running `git add --force --all .`
Running `git write-tree`
  => cf571ab5096f47d4cc637af70fc706b3ccdd9acc
Error on `git commit-tree -p "refs/heads/deploy" -m "Commit build products" cf571ab5096f47d4cc637af70fc706b3ccdd9acc`:
  
Failed to create build products commit for `deploy`
```

I'm trying to follow this guide: http://strong-pm.io/prod/

Any idea about what I'm doing wrong?

I would like to deploy to production a node.js app to a centos 7 server with node v0.12 using nginx as a web server, any suggestion, tutorial or something helpful?

Thanks in advance!

**Comment by sam-github** [comment]
Is this a public repo? Can we run it ourselves to investigate? Its hard to guess what git didn't like.

As a work-around, you can do `slc build --npm` to build a npm packfile, and then deploy that.

See http://docs.strongloop.com/display/SLC/Configuring+Nginx+load+balancer, and other docs around it.

**Comment by carloscarcamo** [comment]
I'm learning about strongloop devops tools and I'm trying to build this repo:
https://github.com/strongloop/express-example-app

I have: git version 1.7.10.4

**Comment by carloscarcamo** [comment]
I resolved this problem updating my git version, 
The docs http://docs.strongloop.com/display/SLC/Committing+a+build+to+Git say:

"To commit a build to a Git repository, you must have Git 1.7.9 or later."

But with my git version 1.7.10 didn't work, so I have updated git to v1.9.1 and now it works great :)

```
$ slc build
Not merging HEAD into `deploy`, already up to date.
Running `npm install --ignore-scripts`
Running `npm prune --production`
Running `git add --force --all .`
Running `git write-tree`
  => 6137e30db896f2ae1ebd66e19ca3fa4d809c3904
Running `git commit-tree -p "refs/heads/deploy" -m "Commit build products" 6137e30db896f2ae1ebd66e19ca3fa4d809c3904`
Running `git update-ref "refs/heads/deploy" 4673240eb7f3a352b0763694ac0cb71440333a50`
Committed build products onto `deploy`
```
