### ISSUE TITLE
Upgrade the version of node inspection in cli.

### ISSUE THREAD

**Issue by harshil93** [strongloop/strongloop#231]
The current version of node-inspector in strongloop@4.0.3 is node-inspector@0.7.4

The 0.7.4 version has a bug which doesn't explode variables when inspecting them. See this SO post for reference
http://stackoverflow.com/questions/28212529/node-inspector-not-exploding-object-properties

Kindly update the node-inspector version.

**Comment by rmg** [comment]
See discussion in #185
