### ISSUE TITLE
StrongLoop Installation fails in Windows 7

### ISSUE THREAD

**Issue by PreethiBabu87** [strongloop/strongloop#236]
Hi 
Am not able to install strongloop in my windows7 machine. This package depends on apackage called Unicode and doesn't that package also doesn't get installed when I tried to install separately. Below is the error log:
--------------------------------
browser bundle successfully generated
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "node" "C:\\Users\\pm18094\\AppData\\Roaming\\npm\\node_modules\\n
pm\\bin\\npm-cli.js" "install" "-g" "strongloop"
npm ERR! node v0.12.4
npm ERR! npm  v2.11.1
npm ERR! code ELIFECYCLE
npm ERR! unicode@0.6.1 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the unicode@0.6.1 postinstall script 'node install.js'.
npm ERR! This is most likely a problem with the unicode package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls unicode
npm ERR! There is likely additional logging output above.

Error log below is when I tried to install Unicode separately:
---------------------------------------------------------------------------------
> unicode@0.6.1 postinstall C:\Users\pm18094\AppData\Roaming\npm\node_modules\un
icode
> node install.js
try to read file /usr/share/unicode/UnicodeData.txt .
/usr/share/unicode/UnicodeData.txt not found.
try to read file /usr/share/unicode-data/UnicodeData.txt .
/usr/share/unicode-data/UnicodeData.txt not found.
try to read file UnicodeData.txt .
UnicodeData.txt not found.
try to download .
GET unicode.org:80/Public/UNIDATA/UnicodeData.txt
Error while downloading UnicodeData.txt: Error: getaddrinfo ENOTFOUND unicode.or
g
Please download file manually, put it next to the install.js file and run `node
install.js` again.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "node" "C:\\Users\\pm18094\\AppData\\Roaming\\npm\\node_modules\\n
pm\\bin\\npm-cli.js" "install" "-g" "unicode"
npm ERR! node v0.12.4
npm ERR! npm  v2.11.1
npm ERR! code ELIFECYCLE
npm ERR! unicode@0.6.1 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the unicode@0.6.1 postinstall script 'node install.js'.
npm ERR! This is most likely a problem with the unicode package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls unicode
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\System32\npm-debug.log

**Comment by rmg** [comment]
This seems to be a recurring problem: dodo/node-unicodetable#16
And it looks like it might be especially bad on Windows: dodo/node-unicodetable#18

@seanbrookes perhaps there is an alternative to the `slug` module that Arc uses that doesn't depend on `unicode`?

**Comment by seanbrookes** [comment]
the slug dependency may not be needed at all.  I think it came over during the concurix prototyping and may have just stuck around...will check out if its even needed anymore

**Comment by rmg** [comment]
@seanbrookes see https://github.com/strongloop/strong-arc/pull/1345

**Comment by rmg** [comment]
@PreethiBabu87 we're working on a fix to remove that dependency. In the mean time, unicode.org seems to be back up and running if you want to try `npm cache clear && npm install -g strongloop` again.
