### ISSUE TITLE
The command slc run was not compatible with the crontab in linux

### ISSUE THREAD

**Issue by xinshouke** [strongloop/strongloop#240]
I hope do a timer task in linux, but I set the command 'slc run' into crontab, the timer doesn't work totally. I had to set 'node server' into crontab, the task may work well! But I need define multiple CPUs thr command 'slc run'. Would you tell me how to do please?

**Comment by rmg** [comment]
@xinshouke what errors do you see in your crontab log when using `slc run`? Is your cron job running in the correct location? Does your crontab's PATH environment variable include the location that the `slc` binary is in?

**Comment by xinshouke** [comment]
I don't know how to check crontab log,let me google it and check this issue later. But I set node server.js, the crontab work well.

**Comment by rmg** [comment]
@xinshouke understood. Unfortunately we need some sort of error message to have any idea what is going wrong.

Depending on your OS, cron logs are either in their own file (`/var/log/cron` or similar) or logged to the general syslog log (something like `/var/log/messages` or `/var/log/syslog`).

Note that `slc run` is intended for long running server applications that accept network connections and is generally not suitable for the kinds of periodic or one-off tasks that are run as cron jobs.

**Comment by xinshouke** [comment]
@rmg I edit my cron as below using the command 'crontab  -e'
55 21 * * * /root/hutuo/STSLC.sh;
vi STSLC.sh as below:
cd /root/hutuo
slc run>> /root/hutuo/ls.txt&
After 21:55, I had not found the node was executed . the log file named /var/log/cron as below:
(root)
Jul 25 21:55:01 iZ2316cy6xxZ CROND[31373]: (root) CMD (/root/hutuo/STSLC.sh)
Jul 25 22:00:01 iZ2316cy6xxZ CROND[31382]: (root) CMD (/usr/lib64/sa/sa1 1 1)
Jul 25 22:01:01 iZ2316cy6xxZ CROND[31386]: (root) CMD (run-parts /etc/cron.hourly)
Jul 25 22:01:01 iZ2316cy6xxZ run-parts(/etc/cron.hourly)[31386]: starting 0anacron
Jul 25 22:01:01 iZ2316cy6xxZ run-parts(/etc/cron.hourly)[31395]: finished 0anacron
Jul 25 22:10:01 iZ2316cy6xxZ CROND[31398]: (root) CMD (/usr/lib64/sa/sa1 1 1)

**Comment by sam-github** [comment]
So, you problem is solved, or not? I notice you didn't include ls.txt, and you don't redirect stderr to ls.txt, so you won't see errors.

Also, its a bit of a mystery still why you are using `slc run` for a short-lived cron task, why don't you just use node?

**Comment by xinshouke** [comment]
@sam-github  Because I hope using multiple CPUs thr command 'slc run'; , there is blank  in my ls.txt file...

**Comment by sam-github** [comment]
That won't work. `slc run` will need a --cluster option to enable clustering, and once you enable cluster, every time one of your workers exits, it will be restarted.... so the app won't ever die, which means every time the crontab starts the app you will have one more instance of the app.
