### ISSUE TITLE
Optional dependencies need updating

### ISSUE THREAD

**Issue by rmg** [strongloop/strongloop#251]
With the release of node-v4.0.0 and the resulting major and minor releases of many modules across the node ecosystem, our the optionalDependencies optimization hack introduced in #213 needs to be updated.

Basically that means resetting the `optionalDependencies` list to `{}`, running a fresh installation, and then adding highly duplicated dependencies to the list. The biggest impact items are any modules that involve binary addons, such as `ws@^0.8.0`, `sqlite3@^3.1.0`, etc.

**Comment by sam-github** [comment]
async and lodash and eslint and tap all could use bringing up to the same version, too.

**Comment by smartmouse** [comment]
just trying SLES 11 SP4  with 64 bit node 4.2.1
Still tons of errors:  
https://gist.github.com/smartmouse/ced7759766a276c124c0

**Comment by rmg** [comment]
Looks like tedeh/jayson#58 has been landed and released as jayson@1.2.2, so that takes care of our final jsonstream/JSONStream warning :-)

**Comment by sam-github** [comment]
@rmg should this be closed now?
