### ISSUE TITLE
slc loopback:model damage my middleware configuration

### ISSUE THREAD

**Issue by rkmax** [strongloop/strongloop#254]
I'm using the following middleware setup

## `middleware.json`
```
{
  ...
  "files": {
    "loopback#static": [
       {"params": "$!../.tmp/", "name": "styles"},
       {"params": "$!../client/", "name": "assets"},
       {"params": "$!../", "name": "vendors"}
     ]
  }
}
```

## `middleware.production.js`
```
module.exports = {
  files: {
    'loopback#static': [
      {name: 'assets', params: '$!../dist/'},
      {name: 'vendors', params: null}
    ]
  }
};
```

as you can see i'm using the name to avoid serving files from some routes if my app it's on production

Now when I ran commands like `slc loopbck:model` my middleware.json left in this state
```
{
  ...
  "files": {
    "loopback#static": [
      {
        "params": "$!../.tmp/"
      },
      {
        "params": "$!../client/ngapp/"
      },
      {
        "params": "$!../"
      }
    ]
  },
}
```

I can omit this before commit but it's a bit annoying

**Comment by sam-github** [comment]
This would best be opened on github.com/strongloop/loopback

/cc @superkhau

**Comment by superkhau** [comment]
Closing. @rkmax Please comment at https://github.com/strongloop/loopback/issues/1833
