### ISSUE TITLE
Trouble with 'npm install -g strongloop' 

### ISSUE THREAD

**Issue by morana2mo** [strongloop/strongloop#258]
npm install -g strongloop

npm ERR! tar.unpack untar error /Users/morana/.npm/strongloop/5.0.1/package.tgz
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "strongloop"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! path /usr/local/lib/node_modules/strongloop
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/strongloop'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/strongloop']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/strongloop',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/strongloop',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:82:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/morana/npm-debug.log
moranadeMBP:~ morana$ slc loopback
-bash: slc: command not found
moranadeMBP:~ morana$ sudo npm install -g node-gyp
Password:
/usr/local/bin/node-gyp -> /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js
node-gyp@3.0.3 /usr/local/lib/node_modules/node-gyp
├── graceful-fs@4.1.2
├── semver@5.0.3
├── fstream@1.0.8 (inherits@2.0.1)
├── nopt@3.0.4 (abbrev@1.0.7)
├── tar@1.0.3 (inherits@2.0.1, block-stream@0.0.8)
├── osenv@0.1.3 (os-homedir@1.0.1, os-tmpdir@1.0.1)
├── minimatch@1.0.0 (sigmund@1.0.1, lru-cache@2.7.0)
├── which@1.2.0 (is-absolute@0.1.7)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── path-array@1.0.0 (array-index@0.1.1)
├── glob@4.5.3 (inherits@2.0.1, once@1.3.2, inflight@1.0.4, minimatch@2.0.10)
├── rimraf@2.4.3 (glob@5.0.15)
├── npmlog@1.2.1 (ansi@0.3.0, are-we-there-yet@1.0.4, gauge@1.2.2)
└── request@2.64.0 (aws-sign2@0.5.0, forever-agent@0.6.1, tunnel-agent@0.4.1, oauth-sign@0.8.0, caseless@0.11.0, stringstream@0.0.4, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, tough-cookie@2.2.0, node-uuid@1.4.3, qs@5.1.0, mime-types@2.1.7, combined-stream@1.0.5, form-data@1.0.0-rc3, http-signature@0.11.0, bl@1.0.0, hawk@3.1.0, har-validator@1.8.0)
moranadeMBP:~ morana$ sudo npm install -g json-file-plus@3.0.0
json-file-plus@3.0.0 /usr/local/lib/node_modules/json-file-plus
├── is@3.1.0
├── node.extend@1.1.5
└── promiseback@2.0.1 (promise-deferred@2.0.1)

**Comment by rmg** [comment]
It appears you did not use `sudo` when attempting to install `strongloop`.

**Comment by jfrazx** [comment]
rmg is correct, although, if using sudo before installing global npm modules is not desired, and my understanding is that it is not, you should consider reinstalling node with a non-root user.  Check this article for more information on that: http://www.johnpapa.net/how-to-use-npm-global-without-sudo-on-osx/

**Comment by kesavkolla** [comment]
I ran npm -g install strongloop as root user still not able to install.

Node js version: 5.0
npm version: 3.3.12
OS: ubuntu 14.04

**Comment by rmg** [comment]
@kesavkolla what were the errors?

**Comment by fospitia** [comment]
This work with node v4.2.2 but not with v5

sudo npm install -g node-gyp
sudo npm install -g strongloop --unsafe-perm

OS: Fedora 22

**Comment by rmg** [comment]
@fospitia if you were using node-v5.0.0, were you using the version of npm that came bundled with it? If so, it is known not to work. You need to either downgrade npm to 2.x (`npm install -g npm@latest-2`) or upgrade it to a newer 3.x (`npm install -g npm@latest`).

@kesavkolla are you still looking for help?

@morana2mo this issue was originally yours, were you able to get things working?

**Comment by kesavkolla** [comment]
Yes it works with latest npm 3.3.1 version.

**Comment by rmg** [comment]
Closing. @morana2mo if you still need help with your problem feel free to re-open.
