### ISSUE TITLE
Windows Install - Could not find WindowsSDKDir variable from the registry

### ISSUE THREAD

**Issue by ibm-boscoli** [strongloop/strongloop#261]
I've trying to install StrongLoop on windows 7 following the guide here -> https://strongloop.com/strongblog/install-node-js-windows/

At step 5, installing strongloop I'm getting a bunch of the below error

![image](https://cloud.githubusercontent.com/assets/14810992/10734117/127cd574-7bd8-11e5-9023-8dda20257023.png)

Was tying to l
1. https://github.com/strongloop/strongloop/issues/210 (the new VS Express doesn't include C:\Program Files\Microsoft SDKs\Windows\v7.1\bin\Setenv.cmd anymore)
2. https://github.com/nodejs/node-gyp/issues/119 (tried installing new npm-gyp doesn't solve the issue)

Any help is appriciated, thank you so much!

**Comment by ibm-boscoli** [comment]
I just tried installing npm3 thinking it maybe a path issues for windows and read that npm3 may help, still failed with the same error.

**Comment by rmg** [comment]
Did you install the Windows SDK? Or just VS?

BTW, these errors should _not_ be fatal - the installation should be finishing, just with some functionality missing.

**Comment by ibm-boscoli** [comment]
I installed Visual Studio Community 2015 instead of Visual Studio Express 2015, the same error is gone after I installed the right one.  I see other errors, I'll create a new issues instead.  Thanks for helping!
