### ISSUE TITLE
slc start throws an error in OSX related to strong-debugger

### ISSUE THREAD

**Issue by cfjedimaster** [strongloop/strongloop#262]
Following the instructions here, https://docs.strongloop.com/display/SLC/Running+apps+with+slc, it says I can go into an existing app and simply do

    slc start

However, doing so gives me this error, repeated every second or so:

Unexpected exit with 1 from Runner: commit slionicfinal/local-directory
Start Runner: commit slionicfinal/local-directory
module.js:339
    throw err;
    ^

Error: Cannot find module 'strong-debugger/package.json'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/strongloop/node_modules/strong-supervisor/lib/runctl.js:4:23)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
Unexpected exit with 1 from Runner: commit slionicfinal/local-directory

**Comment by rmg** [comment]
This bug should have been fixed a couple weeks ago.

Is this from a recent installation? Or an older installation that you have not yet run `slc start` with yet?

Try re-running `npm install -g strongloop` and seeing if that helps.

**Comment by cfjedimaster** [comment]
I think I install strongloop about a month ago. But "slc -v" returns 5.0.1,
and npm info strongloop version also returns 5.0.1.

On Mon, Oct 26, 2015 at 1:05 PM, Ryan Graham <notifications@github.com>
wrote:

> This bug should have been fixed a couple weeks ago.
>
> Is this from a recent installation? Or an older installation that you have
> not yet run slc start with yet?
>
> Try re-running npm install -g strongloop and seeing if that helps.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/strongloop/strongloop/issues/262#issuecomment-151229389>
> .
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by rmg** [comment]
This problem is in the strong-supervisor dependency, which is versioned separately. The updated version was released 2 weeks ago, so you will need to run `npm install -g strongloop` again to update its dependencies.

**Comment by cfjedimaster** [comment]
That did it, and you've taught me something new to worry about in terms of
seeing if various npm-installed things are up to date. ;)

On Mon, Oct 26, 2015 at 2:33 PM, Ryan Graham <notifications@github.com>
wrote:

> This problem is in the strong-supervisor dependency, which is versioned
> separately. The updated version was released 2 weeks ago, so you will need
> to run npm install -g strongloop again to update its dependencies.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/strongloop/strongloop/issues/262#issuecomment-151259660>
> .
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden
