### ISSUE TITLE
Windows Install - A few errors

### ISSUE THREAD

**Issue by ibm-boscoli** [strongloop/strongloop#264]
Windows 7, Visual Studio Express 2015, follow this guide -> https://strongloop.com/strongblog/install-node-js-windows/

Below error appear during StrongLoop install

LINK : fatal error LNK1194: cannot delay-load 'node.exe' due to import of data symbol '"__declspec(dllimport) const v8::ArrayBuffer::Allocator::`vftable'

![image](https://cloud.githubusercontent.com/assets/14810992/10737765/69e5dac4-7bea-11e5-981e-dedc919ca370.png)

and the below follows

![image](https://cloud.githubusercontent.com/assets/14810992/10737781/7a89d6e6-7bea-11e5-9076-87fec7940cf3.png)

![image](https://cloud.githubusercontent.com/assets/14810992/10737808/a3e83c12-7bea-11e5-8e6e-5c4addd3e63a.png)

**Comment by rmg** [comment]
These are optional, known, and all related to outdated dependencies.
