### ISSUE TITLE
Angular error on slc arc

### ISSUE THREAD

**Issue by yeso126** [strongloop/strongloop#265]
I've fresh instaled strongloop, after opening slc arc I can see the navbar but the app is blank, that is what console shows: 

    Error: [$injector:modulerr] Failed to instantiate module Arc due to:
    [$injector:modulerr] Failed to instantiate module Metrics due to:
    [$injector:nomod] Module 'Metrics' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

**Comment by rmg** [comment]
@yeso126 would you mind reporting this on https://github.com/strongloop/strong-arc/issues ?

**Comment by chulkilee** [comment]
See strongloop/strong-arc#1603
