### ISSUE TITLE
npm install -g strongloop requires lots of RAM

### ISSUE THREAD

**Issue by ismail-s** [strongloop/strongloop#267]
I use [cloud 9](c9.io) for development, and ran the command:

    npm install -g strongloop

It failed as the workspace I use has 512MB RAM. Which apparently isn't enough. As I'm using the free version of cloud 9, I am not able to resize the workspace.

At the very least, it should be made clear in the installation instructions just how much RAM is required to install this package. Although fixing the core problem would be nicer (or just distribute a binary).

![image](https://cloud.githubusercontent.com/assets/3778413/10790608/2b8f7ee0-7d7c-11e5-872d-5ecfce0d8599.png)

**Comment by sam-github** [comment]
We don't have any control over how much memory npm uses. This is a cloud9 issue, IMO, if you can't use npm to install packages from github due to memory limitations.

Also, compilation of binaries isn't done by npm, so binary/not is irrelevant to the npm memory usage. I don't know what memory npm uses, but I assume its to track the dependency tree. I'll run it locally out of curiosity, but npm's memory usage is also out of our control.

What do you actually intend to do with slc? If you are only scaffolding loopback applications, you can just install strong-arc.

**Comment by ismail-s** [comment]
@sam-github I was following http://loopback.io/getting-started/

**Comment by ismail-s** [comment]
Yeah, that didn't work. Tried various combos and whatnot, including

    npm install -g strong-arc

and I kept running out of memory. I'll mention it to cloud 9, see what they say then (you can close this issue if you want). If that doesn't work, then I'll just stick to express.

**Comment by sam-github** [comment]
There isn't anything we can do about npm memory usage or cloud9 memory limits, unfortunately.

You could also just use the Yeoman CLI scaffolding tool directly: `npm install -g generator-loopback`. Even that isn't necessary, of course, you can implement a loopback app without ever using any of the tooling, I always create my models by writing the .json configuration directly, though I understand why some people really like the GUI or CLI tools.

But if cloud9 can't even install a single yeoman generator, you might want to consider your use of cloud9, not loopback! :-)

Btw, I'm surprised you'd consider abandoning loopback so quickly. Installation of dev tools is a one-time problem, usage of a framework is a long-term benefit. If loopback has features you need, you'll be spending many weeks or months reimplementing them on top of express. If loopback doesn't have features you need, of course, then skipping this pain and directly using express would be better.

**Comment by ismail-s** [comment]
Your `npm install -g generator-loopback` thing worked ie didn't burn through all the RAM. I've run out of time today, but before I go, I want to thank you for:

1. Being super-fast with your responses
1. Being detailed and helpful with your responses

Originally I was going to create my REST api with golang, but then I decided that there was more community support for node. And stuff like passport.js looks very promising.

I've just been trying out the auto-generated example, and it works. I agree with you that installation of dev tools is a one-time problem, but as devs, we can make it easier than it currently is (well, kinda-everyone has their own machine configuration with weird issues) (I'm talking in general btw, loopback would have been very easy to setup if my vm didn't have only 512MB RAM...).

**Comment by ismail-s** [comment]
I also see no reason to keep this issue open now, reopen if you disagree.

**Comment by sam-github** [comment]
I'm glad you got going, the loopback community on gitter and the mailing list is pretty active for when you have questions, which you surely will if you continue with it.
