### ISSUE TITLE
node-gyp (node lts 4.2.2)

### ISSUE THREAD

**Issue by giuseppeLeggero** [strongloop/strongloop#269]
At this link:
https://docs.strongloop.com/display/SL/Installing+on+MacOS
you can see:

>During installation, you may see a number of errors from node-gyp if you don't have compiler tools installed. These errors only prevent you from performing certain monitoring and management functions such as CPU profiling and Heap memory profiling with slc; If you need those functions, then install compiler tools before continuing. Otherwise, you can ignore the errors for now.

I solve the issue with npm-shrinkwrap.json 
```
os x yosemite 10.10.5
node 4.2.2
npm 2.14.7
```
download it:
https://www.dropbox.com/s/tvjm5soixxqp5qz/npm-shrinkwrap.json?dl=0

copy the file into strongloop folder
delete node_modules folder
npm install

**Comment by sam-github** [comment]
Sorry, what does shrinkwrap have to do with compiler tools? shrinkwrap will choose specific versions of dependencies... they still need installation. I suspect that what is happening is your shrinkwrap is post-install on a compilerless system, so when you install after shrinkwrap, it doesn't attempt to install any packages that failed the first time because of lack of a compiler.

So, you will indeed not see any compiler errors, but that is because you aren't even trying to install them. This isn't an improvement.

**Comment by giuseppeLeggero** [comment]
NO.  please read carefully, as you write:

>Sorry, what does shrinkwrap have to do with compiler tools? shrinkwrap will choose specific versions of dependencies...

when you download a dependency, that will be compiled eg:
https://github.com/websockets/bufferutil/blob/1.1.0/package.json 

and the compiler give you error like:
```
../node_modules/nan/nan.h:256:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../node_modules/nan/nan.h:661:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../node_modules/nan/nan.h:672:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
```
or other similar error, you should check compiler and compiling file.

my "shrinkwrap.json" chooses dependencies like "bufferutil 1.2.1" and other, 
is important to use updated version of "nan" and so on....

this suspect is wrong (in this case):
> I suspect that what is happening is your shrinkwrap is post-install on a compilerless system, so when you install after shrinkwrap, it doesn't attempt to install any packages that failed the first time because of lack of a compiler.


when you install strongloop with npm install -g, in my nodenv environment node modules is installed into
```
/usr/local/Cellar/node/versions/node-v4.2.2/lib/node_modules/
```
I made npm install inside: 
```
     /usr/local/Cellar/node/versions/node-v4.2.2/lib/node_modules/strongloop
``` 
folder.

ps: 
> no cached modules, 
> only module inside  /usr/local/Cellar/node/versions/node-v4.2.2/lib/node_modules/  is: 
> node-gyp 
> npm
