### ISSUE TITLE
Not sure if installed strongloop successfully

### ISSUE THREAD

**Issue by andziaoo7** [strongloop/strongloop#275]
Hi everyone! 
I was trying to install strongloop but I got some errors during this. So I typed command npm install --force -g strongloop and I think that installation was finished successfully but in the console I've found this:

c:\program files\nodejs\node_modules\strongloop\node_modules\strong-arc\node_mo
dules\strong-pm\node_modules\strong-supervisor\node_modules\strong-fork-syslog\
node-syslog.h(8): fatal error C1083: Cannot open include file: 'syslog.h': No s
uch file or directory [C:\Program Files\nodejs\node_modules\strongloop\node_mod
ules\strong-arc\node_modules\strong-pm\node_modules\strong-supervisor\node_modu
les\strong-fork-syslog\build\syslog.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\ankala\AppData\Roaming\nvm\v
0.12.7\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\Users\ankala\AppData\Roaming\nvm\v0.12.7\node
_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Program Files\nodejs\node_modules\strongloop\node_modules\strong
-arc\node_modules\strong-pm\node_modules\strong-supervisor\node_modules\strong-f
ork-syslog
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok

After these errors all process of intallation went ok and that't why I'm not completely sure if I installed strongloop or not. 
Thanks for any hep

**Comment by andziaoo7** [comment]
It turned out that these fatal errors had impact on strongloop although the intallation  process finished with success. I cannot run slc and create model so I install again loopback but this time I typed "$ npm install loopback" without -g and installation went smoothly without any errors :)

**Comment by sam-github** [comment]
You are using a very old version of supervisor, it depends on a package we no longer use: `strong-supervisor\node_modules\strong-fork-syslog`. This is odd, could you please `npm cache clear; npm install -g strongloop` to try a fresh re-install and see if npm installs the most recent code, as it should?

**Comment by rmg** [comment]
@sam-github the old version of strong-supervisor is pulled in from strong-pm from strong-arc

**Comment by rmg** [comment]
This issue seems to have gone stale. Please re-open if it is still a problem.
