### ISSUE TITLE
relational database: source field name option in relation configuration

### ISSUE THREAD

**Issue by dpundir** [strongloop/strongloop#277]
<b>Support of source(keyFrom) field name option in relation configuration i.e. source.sourceKey -> target.targetKey</b>

<b>Example:</b>
"Customer" model configuration can have below relation config:
  "relations": {
    "address":{
      "type": "hasOne",
      "model": "Address",
      "foreignKey": "id"
    }
  }

This relation gets its foreignKey values from primary key("id") of the model i.e. <b>Customer.id -> Address.id</b>. There should be "keyFrom" option to find "pk" like below:
RelationDefinition.hasOne = function (modelFrom, modelTo, params) {
  params = params || {};
  modelTo = lookupModelTo(modelFrom, modelTo, params);

  var pk = <b>params.keyFrom</b> || params.primaryKey || modelFrom.dataSource.idName(modelFrom.modelName) || 'id';

This "keyFrom" can be included in "relations" configuration like below:
  "relations": {
    "address":{
      "type": "hasOne",
      "model": "Address",
      "foreignKey": "id",
      <b>"keyFrom":"addressid"</b>
    }
  }
<b>Customer.keyFrom -> Address.id</b> which makes it truly relational.

**Comment by raymondfeng** [comment]
@dpundir We already support the `primaryKey`. See https://github.com/strongloop/loopback-datasource-juggler/commit/d0f9b760f5a58228c66580ecf80611a21f08c5c9

**Comment by dpundir** [comment]
This should not be closed.
"primaryKey" generally is "id" field of the table. What i am pointing here, is actual foreignkey in referencing table(i.e. customer).
Current design only supports fetching related data based on referencing table primaryKey. If the primaryKey is not in sync in both tables then it gives incorrect results.
like customer id 1 is referencing address id 2 but current design will search address having id 1 which is wrong.
What i am proposing here is addition of "foreignKey" in referencing table i.e. customer, lets say "addressid" which is having primary key of "address" table.
There might be situations when related tables is not having the same primarykey id value as the referencing table's primary key.
