### ISSUE TITLE
relational database: source field name option in relation configuration

### ISSUE THREAD

**Issue by dpundir** [strongloop/strongloop#278]
Related to #277 
"primaryKey" generally is "id" field of the table. There should be support of actual foreignkey in referencing table.
Current design only supports fetching related data based on referencing table primaryKey. If the primaryKey is not in sync in both tables then it gives incorrect results.
like customer id 1 is referencing address id 2 but current design will search address having id 1 which is wrong.
What i am proposing here is addition of "foreignKey" in referencing table i.e. customer, lets say "addressid" which is having primary key of "address" table.
There might be situations when related tables is not having the same primarykey id value as the referencing table's primary key.

**Comment by sam-github** [comment]
Please open this against http://github.com/strongloop/loopback, or perhaps the juggler, where is best @superkhau ?

**Comment by dpundir** [comment]
I opened issue #794 on "loopback-datasource-juggler" as the file "relation-definition" belongs to them.
