### ISSUE TITLE
Typo in Documentation 

### ISSUE THREAD

**Issue by pvijeh** [strongloop/strongloop#281]
https://strongloop.com/strongblog/best-practices-express-js-process-manager/

This article has a typo in one of the commands.  This command reads: 

peter@loopback-api2:~$ slc pm -l 7777
sl-pm(1674): StrongLoop PM v5.1.0 (API v6.1.0) on port `7777`
sl-pm(1674): Base folder `/home/peter/.strong-pm`
sl-pm(1674): Applications on port `3000 + service ID`
Browse your REST API at http://127.0.0.1:7777/explorer

but it should read:

peter@loopback-api2:~$ sl-pm -l 7777
sl-pm(1674): StrongLoop PM v5.1.0 (API v6.1.0) on port `7777`
sl-pm(1674): Base folder `/home/peter/.strong-pm`
sl-pm(1674): Applications on port `3000 + service ID`
Browse your REST API at http://127.0.0.1:7777/explorer

**Comment by crandmck** [comment]
Thanks for noticing!  I fixed this.
