### ISSUE TITLE
slc command not found after install 

### ISSUE THREAD

**Issue by mostlycarbonite** [strongloop/strongloop#286]
Same issue but not a resolution: https://github.com/strongloop/strongloop/issues/127

Steps: 
```
$ npm install -g strongloop
... [installs successfully, some warnings] 
$  ll /usr/local/bin | grep strong
lrwxrwxrwx 1 collumj dsunixuser       42 Jan  8 17:45 slpm -> ../lib/node_modules/strong-pm/bin/sl-pm.js
lrwxrwxrwx 1 collumj dsunixuser       42 Jan  8 17:45 sl-pm -> ../lib/node_modules/strong-pm/bin/sl-pm.js
lrwxrwxrwx 1 collumj dsunixuser       45 Jan  8 17:45 slpmctl -> ../lib/node_modules/strong-pm/bin/sl-pmctl.js
lrwxrwxrwx 1 collumj dsunixuser       45 Jan  8 17:45 sl-pmctl -> ../lib/node_modules/strong-pm/bin/sl-pmctl.js
lrwxrwxrwx 1 collumj dsunixuser       50 Jan  8 17:45 sl-pm-install -> ../lib/node_modules/strong-pm/bin/sl-pm-install.js
$ slc
-bash: slc: command not found
$ npm install -g semver
$ semver -h
SemVer 5.1.0

A JavaScript implementation of

```

This is a fresh server running CentOS 7. I may have missed some steps or goofed up the node install. But `semver` seems to be fine. I can start up `sl-pm` with no issues.

**Comment by smartmouse** [comment]
which node version and which npm version?

**Comment by mostlycarbonite** [comment]
```
$ node --version
v4.2.3
$ npm --version
1.3.6
```

**Comment by rmg** [comment]
There is definitely something weird going on!

@mostlycarbonite how/why are you using such an ancient version of npm? You also appear to have installed the strongloop module's dependencies without installing _it_. `npm install -g strongloop` shouldn't even be creating bin commands for `sl-pm`, `sl-pm-install`, etc..

How did you install node and npm?

**Comment by mostlycarbonite** [comment]
Damn, I just realized that npm is very outdated. What the heck! Investigating...

**Comment by mostlycarbonite** [comment]
Checked my notes, looks like I had used `yum` to install npm; part of troubleshooting why node hadn't installed correctly on a fresh CentOS 7 box. Yum's version must be very outdated. Uninstalled npm via yum, then uninstalled node, then installed node via nvm, then install strongloop tools and it's all working fine now.

**Comment by smartmouse** [comment]
The default npm version for node 4.2.3 should be 2.14.7. How come you have such an old npm version? I do not have CentOS 7.1 OS , just other linux system. I can install -g strongloop  and have slc running w/o issue.  May  be you can update your npm .

lrwxrwxrwx 1 strongbot user       41 Jan  7 22:48 slc -> ../lib/node_modules/strongloop/bin/slc.js

-bash-4.2$ slc -v
strongloop v6.0.0 (node v4.2.3)
├── strong-arc@1.8.5 (d01942e)
├── strong-build@2.1.0 (47dd24a)
├── strong-deploy@3.1.2 (be6180a)
├── strong-mesh-models@8.1.0 (62e539b)
├── strong-pm@5.1.0 (eb2f788)
├── strong-registry@1.1.5 (f46e58f)
├── strong-start@1.3.2 (1327018)
├─┬ strong-supervisor@3.3.1 (1e39220)
│ └── strong-agent@2.0.2 (4ea7ee9)
├── generator-loopback@1.13.0 (a884c0b)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3

**Comment by ytimocin** [comment]
I have the same issue. I installed strongloop by "npm install -g strongloop" but:
$ slc loopback
-bash: slc: command not found

my node and npm versions are as follows:
$ node --version
v0.12.2
$ npm --version
3.6.0

Is there any solution?

**Comment by rmg** [comment]
@ytmocin what does `npm ls -g --depth=0` show? Do you have npm configured to use a global module location that is not included in your `$PATH`?

**Comment by ytimocin** [comment]
@rmg I uninstalled node and npm, downloaded the final version and installed again.
after some permission grants, I installed strongloop. but guess what? DIDNOT WORK! :)
this post helped me solve my problem: http://stackoverflow.com/questions/14803978/npm-global-path-prefix

now strongloop works perfectly.

**Comment by youngtk96** [comment]
I know this post is old but this solution did not fix my issue. **What i did to resolve this issue** is to make sure you are running power shell or Git Bash as an administrator. If you are on Ubuntu make sure you run SUDO
