### ISSUE TITLE
Installation Error - Node.js Version

### ISSUE THREAD

**Issue by developersencha** [strongloop/strongloop#289]
The installation of Strongloop fails with node.js version 4.2.4 LTS.
Trying with the versions I found that v.0.12.7 is ok.
What is the maximum version of node that strongloop installs properly?
Is any other way to install strongloop with node.js version >=4.0.0?

**Comment by sam-github** [comment]
We support at least the latest of all the major versions: 0.10, 0.12, v4.x, v5.x, and it just installed for me with node.js 4.2.4 and Ubuntu. 

Can you describe what failed?

**Comment by developersencha** [comment]
I have Windows 8.1 and after I disabled the AVG antivirus, I managed to install strongloop with node.js version 4.2.4 LTS. Probably this was the cause (although doesn't explain why I installed it with v.0.12.7). 

Thanks for your time
