### ISSUE TITLE
Update node-inspector dependency

### ISSUE THREAD

**Issue by wision** [strongloop/strongloop#290]
Hello,

any chance of updating node-inspector dependency? I'm experiencing `Uncaught TypeError: window.getComputedStyle(...).getPropertyCSSValue is not a function` which was fixed in node-inspector more than a year ago, but current version is even older. Thank you.

**Comment by rmg** [comment]
There was _some_ discussion in #185. There were problems last time it was looked into.

**Comment by wision** [comment]
Sorry, I must have missed that pull request.. thanks for the information.

**Comment by rmg** [comment]
Closing since this issue predates https://github.com/nodejs/node-inspect
