### ISSUE TITLE
Does  strongloop support es6  yield style with model query function ? 

### ISSUE THREAD

**Issue by toplinuxsir** [strongloop/strongloop#292]
for example with es6 syntax and babel translate:
  function query() {
   var reslt  =      yield Model.find({filed:fieldValue});
   console.log(result);
}

**Comment by rmg** [comment]
Closing as a stale issue. If no answer was found elsewhere, please try asking on Stackoverflow, the loopbackjs mailing list, or opening an issue on https://github.com/strongloop/loopback.
