### ISSUE TITLE
Errors on strongloop install

### ISSUE THREAD

**Issue by Joesimonsen** [strongloop/strongloop#296]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#1356](https://strongloop.zendesk.com/agent/tickets/1356)
**Priority:** N/A
**Group:** SL Support
**Assignee:** Samuel Thompson
**Support Type:** prospect
**Case Type:** 
**Component:** 
**Severity:** 
**CritSit Update:** 
**GitHub ID:** 
**IBM CIN Number:** 

**Original ticket description:**

<blockquote><div class="zd-comment">
<p>(See attached file: npm-debug.log.zip)</p>

<p>Hi guys, i’m trying to make a fresh installation of strongloop, but i can’t. Here are the details:</p>

<p>Specs:
<br>OSX 10.11.3
<br>node v5.4.1
<br>npm v3.7.1</p>

<p>Steps:
<br>sudo chown -R $USER /usr/local/bin
<br>sudo chown -R $USER /usr/local/lib/node_modules
<br>sudo npm install -g strongloop</p>

<p>Errors:
<br>/usr/local/lib
<br>`-- (empty)</p>

<p>npm ERR! Darwin 15.3.0
<br>npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "strongloop"
<br>npm ERR! node v5.4.1
<br>npm ERR! npm  v3.7.1
<br>npm ERR! path /usr/local/lib/node_modules/.staging/aws-sign-5f4cf298
<br>npm ERR! code ENOENT
<br>npm ERR! errno -2
<br>npm ERR! syscall rename</p>

<p>npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/aws-sign-5f4cf298' -&gt; '/usr/local/lib/node_modules/strongloop/node_modules/nodefly-register/node_modules/request/node_modules/aws-sign'
<br>npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/aws-sign-5f4cf298' -&gt; '/usr/local/lib/node_modules/strongloop/node_modules/nodefly-register/node_modules/request/node_modules/aws-sign'
<br>npm ERR! enoent This is most likely not a problem with npm itself
<br>npm ERR! enoent and is related to npm not being able to find a file.
<br>npm ERR! enoent </p>

<p>npm ERR! Please include the following file with any support request:
<br>npm ERR!     /Users/Gonzalo/Sites/npm-debug.log
<br>npm ERR! code 1</p>

<p>Do i neeed something from AWS?
<br>I also downloaded thee vagrant file the community provide but it also fails because a “bootstrap.sh” file is missing. I already check for this issue in github and it’s reported but with no answer. <a href="https://github.com/strongloop-community/vagrant-strongnode/issues" rel="nofollow noreferrer" target="_blank">https://github.com/strongloop-community/vagrant-strongnode/issues</a>
<br>I’m attaching the log as well.</p>

<p>--
<br>Gonzalo Vega
<br>Wit-Labs
<br>02 2704 5096
<br><a href="mailto:gvega@wit-labs.com" rel="noreferrer">gvega@wit-labs.com</a></p>
</div></blockquote>

#### Attachments
- [npm-debug.log.zip](https://strongloop.zendesk.com/attachments/token/BP1IrHhkslJygBnrPZSPaZ9Vv/?name=npm-debug.log.zip)

**Comment by Joesimonsen** [comment]
*Comment made from Zendesk by Samuel Thompson on 2016-02-09 at 17:23:*

<blockquote><div class="zd-comment">
<p>Hi Gonzalo,</p>
<p>Could you try running these commands?</p>
<pre><code>sudo chown -R $USER /usr/local/bin
sudo chown -R $USER /usr/local/lib/node_modules
npm install -g strongloop
</code></pre>
<p>It's identical to your steps except we've taken the <code>sudo</code> off of the front of the <code>npm install</code>.</p>
<p>Let me know if you manage to get anything different from that.</p>
<p>Sam</p>
</div></blockquote>

**Comment by Joesimonsen** [comment]
*Comment made from Zendesk by Gonzalo Vega on 2016-02-09 at 18:58:*

<blockquote><div class="zd-comment">
<p>Hi Samuel, it didn’t work.</p>

<p>GoVeM:Sites Gonzalo$ sudo chown -R $USER /usr/local/bin
<br>Password:
<br>GoVeM:Sites Gonzalo$ sudo chown -R $USER /usr/local/lib/node_modules
<br>GoVeM:Sites Gonzalo$ npm install -g strongloop
<br>npm WARN deprecated <a href="mailto:lodash@2.4.2" rel="noreferrer">lodash@2.4.2</a>: lodash@&lt;3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0
<br>/usr/local/lib
<br>`-- (empty)</p>

<p>npm ERR! Darwin 15.3.0
<br>npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "strongloop"
<br>npm ERR! node v5.4.1
<br>npm ERR! npm v3.7.1
<br>npm ERR! path /usr/local/lib/node_modules/.staging/aws-sign-5f4cf298
<br>npm ERR! code ENOENT
<br>npm ERR! errno -2
<br>npm ERR! syscall rename</p>

<p>npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/aws-sign-5f4cf298' -&gt; '/usr/local/lib/node_modules/strongloop/node_modules/nodefly-register/node_modules/request/node_modules/aws-sign'
<br>npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/aws-sign-5f4cf298' -&gt; '/usr/local/lib/node_modules/strongloop/node_modules/nodefly-register/node_modules/request/node_modules/aws-sign'
<br>npm ERR! enoent This is most likely not a problem with npm itself
<br>npm ERR! enoent and is related to npm not being able to find a file.
<br>npm ERR! enoent </p>

<p>npm ERR! Please include the following file with any support request:
<br>npm ERR! /Users/Gonzalo/Sites/npm-debug.log
<br>npm ERR! code 1</p>

<p>--
<br>Gonzalo Vega
<br>Wit-Labs
<br>02 2704 5096
<br><a href="mailto:gvega@wit-labs.com" rel="noreferrer">gvega@wit-labs.com</a></p>

<p>&gt; El 09-02-2016, a las 2:23 p.m., StrongSupport &lt;<a href="mailto:support@strongloop.zendesk.com" rel="noreferrer">support@strongloop.zendesk.com</a>&gt; escribió:</p>
</div></blockquote>

**Comment by Joesimonsen** [comment]
*Comment made from Zendesk by Samuel Thompson on 2016-02-09 at 19:51:*

<blockquote><div class="zd-comment">
<p>Hi Gonzalo,</p>
<p>Can you send me the output of these commands on your system?</p>
<pre><code>npm -v
node -v
ls -1 /usr/local/lib/node_modules/
</code></pre>
<p>Thanks,</p>
<p>Sam</p>
</div></blockquote>

**Comment by Joesimonsen** [comment]
*Comment made from Zendesk by Gonzalo Vega on 2016-02-09 at 19:57:*

<blockquote><div class="zd-comment">
<p>GoVeM:Sites Gonzalo$ npm -v
<br>3.7.1
<br>GoVeM:Sites Gonzalo$ node -v
<br>v5.4.1
<br>GoVeM:Sites Gonzalo$ ls -1 /usr/local/lib/node_modules/
<br>aws-sign
<br>forever
<br>generator-angular
<br>generator-karma
<br>generator-sails-angular
<br>jade
<br>mocha
<br>n
<br>nodemon
<br>npm
<br>parse-develop
<br>sails
<br>should
<br>strongloop
<br>supertest
<br>supervisor
<br>yo</p>

<p>i installed aws-sign as a test, i don’t need it.</p>

<p>--
<br>Gonzalo Vega
<br>Wit-Labs
<br>02 2704 5096
<br><a href="mailto:gvega@wit-labs.com" rel="noreferrer">gvega@wit-labs.com</a></p>

<p>&gt; El 09-02-2016, a las 4:51 p.m., StrongSupport &lt;<a href="mailto:support@strongloop.zendesk.com" rel="noreferrer">support@strongloop.zendesk.com</a>&gt; escribió:</p>
</div></blockquote>

**Comment by Joesimonsen** [comment]
*Comment made from Zendesk by Samuel Thompson on 2016-02-09 at 21:25:*

<blockquote><div class="zd-comment">
<p>Hi Gonzalo,</p>
<p>Looks like everything is good so far, can you run this last command pates the output here?</p>
<pre><code>slc -v
</code></pre>
<p>If that's giving you the versions of everything installed, see if you can run these commands:</p>
<pre><code>mkdir ~/loopback-test
cd ~/loopback-test
slc loopback:app
</code></pre>
<p>Let me know what happens there. If we can't figure this out, I am going to escalate this to the development team as I would suspect it could be an issue with the strongloop package itself.</p>
<p>Cheers,<br>
Sam</p>
</div></blockquote>

**Comment by Joesimonsen** [comment]
*Comment made from Zendesk by Gonzalo Vega on 2016-02-09 at 21:28:*

<blockquote><div class="zd-comment">
<p>No luck.</p>

<p>GoVeM:Sites Gonzalo$ slc -v
<br>-bash: slc: command not found</p>

<p>--
<br>Gonzalo Vega
<br>Wit-Labs
<br>02 2704 5096
<br><a href="mailto:gvega@wit-labs.com" rel="noreferrer">gvega@wit-labs.com</a></p>

<p>&gt; El 09-02-2016, a las 6:25 p.m., StrongSupport &lt;<a href="mailto:support@strongloop.zendesk.com" rel="noreferrer">support@strongloop.zendesk.com</a>&gt; escribió:</p>
</div></blockquote>

**Comment by Joesimonsen** [comment]
*Comment made from Zendesk by Samuel Thompson on 2016-02-09 at 21:37:*

<blockquote><div class="zd-comment">
<p>Gonzalo,</p>
<p>I am escalating this to the developers, they should be able to offer some insight here.</p>
<p>Cheers,<br>
Sam</p>
</div></blockquote>

**Comment by Joesimonsen** [comment]
*Comment made from Zendesk by Gonzalo Vega on 2016-02-09 at 21:38:*

<blockquote><div class="zd-comment">
<p>Thank you very much.
<br>Have a nice day.</p>

<p>--
<br>Gonzalo Vega
<br>Wit-Labs
<br>02 2704 5096
<br><a href="mailto:gvega@wit-labs.com" rel="noreferrer">gvega@wit-labs.com</a></p>

<p>&gt; El 09-02-2016, a las 6:37 p.m., StrongSupport &lt;<a href="mailto:support@strongloop.zendesk.com" rel="noreferrer">support@strongloop.zendesk.com</a>&gt; escribió:</p>
</div></blockquote>

**Comment by jfrazx** [comment]
I had a similar issue. 

```
/usr/local/lib
└── (empty)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.0.0/bin/node" "/usr/local/bin/npm" "install" "-g" "strongloop"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.9
npm ERR! path /usr/local/lib/node_modules/.staging/aws-sign-5f4cf298
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/aws-sign-5f4cf298' -> '/usr/local/lib/node_modules/strongloop/node_modules/nodefly-register/node_modules/request/node_modules/aws-sign'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/aws-sign-5f4cf298' -> '/usr/local/lib/node_modules/strongloop/node_modules/nodefly-register/node_modules/request/node_modules/aws-sign'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 
```

slc was available afterward though. 

```
$ slc   
usage: slc <-h|--help|-v|--version>    
etc...
```

Attempting to utilize slc would result in errors.

```
$ slc loopback 
Error loading module "loopback":
 { Error: Cannot find module 'rx'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/strongloop/node_modules/inquirer/lib/utils/utils.js:8:10)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3) code: 'MODULE_NOT_FOUND' }
```

Installed rx 

`$ npm install -g rx`

Running again 

```
$ slc loopback 
Error loading module "loopback":
 { Error: Cannot find module 'findup-sync'
etc...
```

Same deal for others, so: 

```
$ npm install -g findup-sync 
$ npm install -g loopback 
$ npm install -g loopback-datasource-juggler 
```

Then

```
$ slc loopback 
Error loading module "loopback":
 TypeError: Cannot convert undefined or null to object
```

So I uninstalled

`$ npm uninstall -g strongloop`

and reinstalled 

`$ npm install -g strongloop`

and now.

```
$ slc loopback
(node:36574) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
loopback deprecated loopback.cookieParser is deprecated. Use `require('cookie-parser');` instead. ../../../../usr/local/lib/node_modules/strongloop/node_modules/loopback-workspace/server/server.js:45:17

     _-----_
    |       |    .--------------------------.
    |--(o)--|    |  Let's create a LoopBack |
   `---------´   |       application!       |
    ( _´U`_ )    '--------------------------'
    /___A___\    
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

? What's the name of your application?
```

Success.

Not sure why it worked, but maybe it will help someone else.

**Comment by rmg** [comment]
Closing, since this appears either resolved or stale. Likely resolved by improvements that have been made to `npm` since this issue was originally opened.

**Comment by Yankee-by** [comment]
I have the same issue.
```
npm -v 5.6.0
node -v 9.4.0
```
`sudo npm i -g strongloop` generate an error:
```

npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated ejs@1.0.0: Critical security bugs fixed in 2.5.5
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated connect@2.30.2: connect 2.x series is deprecated
npm WARN deprecated coffee-script@1.6.3: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! path /usr/local/lib/node_modules/strongloop/node_modules/nodefly-register/node_modules/request/node_modules/aws-sign
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/strongloop/node_modules/nodefly-register/node_modules/request/node_modules/aws-sign' -> '/usr/local/lib/node_modules/strongloop/node_modules/nodefly-register/node_modules/request/node_modules/.aws-sign.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yurygrinko/.npm/_logs/2018-01-29T14_58_08_848Z-debug.log
```
`ls -1 /usr/local/lib/node_modules/` result:
```
npm
strongloop
```
but 
```
slc -v                                                                                          
Unknown command 'slc'
```

**Comment by herbertscruz** [comment]
I also have the same problem.

**Comment by javahaxxor** [comment]
me too

**Comment by woooooopwop** [comment]
Same here

**Comment by javahaxxor** [comment]
> sudo chown -R $USER /usr/local/bin
> sudo chown -R $USER /usr/local/lib/node_modules
> npm install -g strongloop
This worked for me

**Comment by Yankee-by** [comment]
> sudo chown -R $USER /usr/local/bin
> sudo chown -R $USER /usr/local/lib/node_modules
> npm install -g strongloop
> This worked for me
not in my case

**Comment by Yankee-by** [comment]
fixed it this way https://github.com/strongloop/strongloop/issues/354#issuecomment-368386434
