### ISSUE TITLE
404 link in docs - LoopBack core concepts

### ISSUE THREAD

**Issue by cfjedimaster** [strongloop/strongloop#297]
On this page, https://docs.strongloop.com/display/public/LB/LoopBack+core+concepts, the link to "Storage Service" (http://docs.strongloop.com/display/LB/Storage+service) goes to a 404.

**Comment by rmg** [comment]
@crandmck looks like this link is still stale/broken, can you fix it?

**Comment by crandmck** [comment]
Thanks for reporting @cfjedimaster.  Fixed.
The link is https://docs.strongloop.com/display/LB/Storage+component now.
