### ISSUE TITLE
Misleading text in Troubleshooting docs

### ISSUE THREAD

**Issue by cfjedimaster** [strongloop/strongloop#298]
This url, https://docs.strongloop.com/display/APIS/Troubleshooting, under Stuck interface, says:

> If you get Arc into a "bad state," you can "un-stick" it by going to cookies and deleting localhost's localstorage entry.

This is a bit misleading as cookies are not the same as localstorage. Where the person would go in their devtools depends on their browser, but as all the modern browsers support checking LocalStorage, you should just tell them to go there. Although Firefox, at least, does not let you modify the values from the LocalStorage view, you would need to do so in the console.

**Comment by rmg** [comment]
@crandmck we should probably give @cfjedimaster access to edit the docs since he's now part of the team :-)

**Comment by cfjedimaster** [comment]
I'd be fine with that - I may have access already. I know there are about 200 StrongLoop repos so if you wanted to point me in the right direction and assign to me, I'd be happy to. :)

**Comment by crandmck** [comment]
@cfjedimaster Could you please fix this up as you see fit?  This text is pretty old and having the API "get stuck" may not even be an issue any longer.

**Comment by cfjedimaster** [comment]
Ok - I failed - what's the repo for the docs?

**Comment by crandmck** [comment]
@cfjedimaster It's not a GitHub repo, it's a Confluence wiki.
I'll send you email.

**Comment by cfjedimaster** [comment]
Edited.
