### ISSUE TITLE
findOrCreate in loop

### ISSUE THREAD

**Issue by yahoohung** [strongloop/strongloop#300]
I have a interesting problem on loopback. It displayed wrong result when I was adding records with findOrCreate. Let's see the example.

```
for (var x = 0; x < 10; x++) {
    var Log = app.models.Log;
    Log.findOrCreate({
      where: {
        modelName: '123'
      }
    }, {
      modelName: '123'
    }, function(err, log) {});
  }
```

I think it should be create 1 record with modelName '123' only, but I got 10 finally.

Is there something wrong? Thanks.

**Comment by Amir-61** [comment]
Please don't create duplicate tickets; closing in favour of [this ticket](https://github.com/strongloop/loopback/issues/2148)
