### ISSUE TITLE
Logging for slc pm

### ISSUE THREAD

**Issue by jas199** [strongloop/strongloop#305]
Hi,

I am starting strongpm with slc pm command and not via service. 
The application goes down after some number of hits. Can i get the location where the log would be saved?

Now i have started using **nohup slc pm** and the logging is saved to nohup.out file. Now the application is up from a couple of hours and not going down.

Can the application going down be attributed to the slc log being dumped on console when the application is hit and now as it is directed to a file, it not not getting dumped to console?

Urgent help required!

**Comment by rmg** [comment]
Closing since this was either addressed elsewhere or it is simply too late for any response to qualify as "urgent".
