### ISSUE TITLE
defining a delete remote method don't accepts parameters 

### ISSUE THREAD

**Issue by matthieupenchenat81** [strongloop/strongloop#306]
Hello,

I'm trying to define a custom remote method with delete http verb. I managed to do this remote method with a http post verb but not with delete. Is there a particular way to define a delete remote method with parameters?

When I try to set the delete http verb, I can go inside the remote method but pEmail and pTel is undefined...

You can see the following remote method just below:

![capture d ecran de 2016-03-23 14-36-58](https://cloud.githubusercontent.com/assets/6177598/13986857/f321b850-f104-11e5-87a0-792e4a47554f.png)

I hope you'll be able to help me, 
thanks you,
Matthieu.

**Comment by rmg** [comment]
Closing since this issue is quite old and was likely answered somewhere more appropriate such as Stackoverflow.
