### ISSUE TITLE
What is the difference of create and add in referencesMany relation

### ISSUE THREAD

**Issue by JoeShi** [strongloop/strongloop#310]
These are the helper methods listed in [referencesMany](https://docs.strongloop.com/display/APIC/Embedded+models+and+relations#Embeddedmodelsandrelations-ReferencesMany)  relationship. Can someone tell me the difference of `create` and `add`, `destroy` & `remove`?

```
customer.accounts()
customer.accounts.create()
customer.accounts.build()
customer.accounts.findById()
customer.accounts.destroy()
customer.accounts.updateById()
customer.accounts.exists()
customer.accounts.add()
customer.accounts.remove()
customer.accounts.at()

```

**Comment by sam-github** [comment]
@JoeShi best posted against github.com/strongloop/loopback
