### ISSUE TITLE
`http+ssh://` "protocol" is confusing

### ISSUE THREAD

**Issue by Sequoia** [strongloop/strongloop#313]
[This](https://docs.strongloop.com/display/SLC/Securing+Process+Manager#SecuringProcessManager-UsingSSHtunneling) is very confusing as it the URI is using a standard URI scheme called `http+ssh`. In fact, it appears [no such scheme exists](http://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml), or it's not documented.

I spent about an hour attempting to research `http-ssh` this before realizing there is no such URI scheme or protocol. :( This is confusing, as typically `scheme://` is a standard URI scheme.

## Proposal

Change this feature to be called when using the `--tunnel` switch instead of creating a new URI scheme.

**Comment by sam-github** [comment]
It documented in our docs, sorry you were confused, though I'm confused as to why you were spending any time researching it... what were you looking to find? The behaviour is described in the first link you reference.

Non-standard URI scheme's are wide-spread.
