### ISSUE TITLE
Disable the use of `strong-agent` when using `slc start`

### ISSUE THREAD

**Issue by rtodea** [strongloop/strongloop#323]
Because of the issue discussed [here](https://github.com/Automattic/kue/issues/953#issuecomment-251200898), I want to disable the `strong-agent` wrapping of `redis`.

Something like this does not work:

```
slc start
slc ctl tracing-stop <SERVICE_ID>
```

Any suggestions?

**Comment by dkulygin** [comment]
A workaround that works for me is to manually install strong-agent version 2.0.4 for strong-pm.

**Comment by rtodea** [comment]
@dkulygin, how would you install strong-agent version 2.0.4?

I usually do a:
```
npm install strongloop
``` 
to see which versions get installed:
```
slc -v
```

My output:
```
strongloop v6.0.3 (node v6.5.0)
├── strong-arc@1.8.9 (3dd25ac)
├── strong-build@2.1.2 (a98f310)
├── strong-deploy@3.1.4 (9b29df0)
├── strong-mesh-models@8.1.0 (62e539b)
├── strong-pm@5.2.3
├── strong-registry@1.1.6 (f8c2339)
├── strong-start@1.3.4 (28c261d)
├─┬ strong-supervisor@3.3.3
│ └── strong-agent@2.0.4 (de9885e)
├── generator-loopback@1.24.4 (0c6b9c3)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3
```

**Comment by sam-github** [comment]
Underlying issue is https://github.com/strongloop/strongloop/issues/323

Its not possible to disable strong-agent when using strong-pm or `slc start` currently, sorry. It should be, there is internal support, but its not exposed.

We'll fix the underlying issue for now.

**Comment by sam-github** [comment]
issue moved to https://github.com/strongloop/strong-pm/issues/374
