### ISSUE TITLE
Global installation is broken due to sqlite3

### ISSUE THREAD

**Issue by dzonatan** [strongloop/strongloop#324]
`npm install -g strongloop` got broken.

There are a lot of issues describing this error:
strongloop/strong-arc#1733
npm/npm#14188

But they are in the wrong place due to misleading npm error.
The things got broken after `sqlite3` new version `3.1.5` release. 
There is already an issue mapbox/node-sqlite3#720 for that.

The actual dependency to `sqlite3` is in [this package](https://github.com/strongloop/strongloop/blob/master/package.json#L121) therefore I made an issue here.

Maybe PR for locking `sqlite3` to `3.1.4` version would help at least for now?
caret^ is 👿

**Comment by HenrikGr** [comment]
I reported a question on stackoverflow and wonder if this is related to my propblems?
http://stackoverflow.com/questions/39896468/resource-busy-or-locked-when-installing-apiconnect-via-npm

**Comment by rmg** [comment]
Closing since #326 was merged, which pinned the version to 3.1.4.

For extra coverage, it looks like mapbox/node-sqlite3#720 has been resolved (only minutes ago!) by the release of 3.1.6, which should fix the problem for previous releases.
