### ISSUE TITLE
File path or file name too long when installing apiconnect in Windows 10

### ISSUE THREAD

**Issue by HenrikGr** [strongloop/strongloop#328]
I did have a problem with installation of apiconnect the other day, and I think it was resolved by ensure sqlite 3.1.6 was installed instead of 3.1.5. 

After that, my installation goes better but I get an error saying file paths or names are to long.

![apiconnecterror2](https://cloud.githubusercontent.com/assets/11950811/19206449/680ae0bc-8ce9-11e6-80fc-20d1f5518617.PNG)

Laptop:
Windows 10, do not have possibility to edit group policy and enable long file names / path in ntfs. :-(
node.js 4.5.0
npm 3.8.1
Clean installation of node.js, removed npm-cache, installed windows-build-tools.

Do I have to buy a new linux based computer? :-)

**Comment by sam-github** [comment]
Please report to apiconnect if you are installing apiconnect, thanks.
