### ISSUE TITLE
Fails to install "strong-mesh-client@1.6.3 Failed to exec install script"

### ISSUE THREAD

**Issue by janpansa** [strongloop/strongloop#337]
When I install strongloop using npm, I get the following errors, preventing strongloop from installing:
```
npm info strong-mesh-client@1.6.3 Failed to exec install script
npm ERR! Linux 4.9.8-1-ARCH
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "-g" "install" "strongloop"
npm ERR! node v4.7.2
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! strong-mesh-client@1.6.3 install: `node proxy/build-client.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the strong-mesh-client@1.6.3 install script 'node proxy/build-client.js'.
npm ERR! This is most likely a problem with the strong-mesh-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node proxy/build-client.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs strong-mesh-client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls strong-mesh-client
npm ERR! There is likely additional logging output above.
npm info preuninstall strong-mesh-client@1.6.3
npm info uninstall strong-mesh-client@1.6.3
npm info postuninstall strong-mesh-client@1.6.3
npm info preuninstall strong-arc@1.8.9
npm info uninstall strong-arc@1.8.9
npm info postuninstall strong-arc@1.8.9
npm info preuninstall strongloop@6.0.3
npm info uninstall strongloop@6.0.3
npm info postuninstall strongloop@6.0.3

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log
The command '/bin/sh -c npm -g install strongloop' returned a non-zero code: 1
```

**Comment by rmg** [comment]
Upstream as strongloop/strong-mesh-client#53.

**Comment by rmg** [comment]
Up-upstream as request/request#2585.

**Comment by janpansa** [comment]
@rmg Thanks for the help so far. I noticed a new version of strong-mesh-client was released, however, I still receive the same error report :

```
npm info strong-mesh-client@1.6.4 Failed to exec install script
npm ERR! Linux 4.8.13-1-ARCH
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "-g" "install" "strongloop"
npm ERR! node v4.8.0
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! strong-mesh-client@1.6.4 install: `node proxy/build-client.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the strong-mesh-client@1.6.4 install script 'node proxy/build-client.js'.
npm ERR! This is most likely a problem with the strong-mesh-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node proxy/build-client.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs strong-mesh-client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls strong-mesh-client
npm ERR! There is likely additional logging output above.
npm info preuninstall strong-mesh-client@1.6.4
npm info uninstall strong-mesh-client@1.6.4
npm info postuninstall strong-mesh-client@1.6.4
npm info preuninstall strong-arc@1.8.9
npm info uninstall strong-arc@1.8.9
npm info postuninstall strong-arc@1.8.9
npm info preuninstall strongloop@6.0.3
npm info uninstall strongloop@6.0.3
npm info postuninstall strongloop@6.0.3

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log
The command '/bin/sh -c npm -g install strongloop' returned a non-zero code: 1
```

**Comment by janpansa** [comment]
I managed to get it working by using this "npm -g install **--ignore-scripts** strongloop"

**Comment by ccoeurderoy** [comment]
@janpansa Running `npm -g install --ignore-scripts strongloop` works for me too ! To deploy on Heroku, I had to fork **strongloop-buildpacks** and added the same command. Here is my fork for those who are interested : https://github.com/yelloan/strongloop-buildpacks.

**Comment by rmg** [comment]
Unfortunately the `--ignore-scripts` disables scripts that are somewhat important for Arc functionality.

Squashing to source of the issue in `strong-mesh-client` just ended up shifting it to `generator-loopback` as the source of the incompatible version of `request`.

@janpansa @ccoeurderoy if you aren't using Arc then the workaround you are using _should_ be ok.

**Comment by sam-github** [comment]
If you aren't using Arc, you shouldn't be using the "strongloop" build pack!

**Comment by janpansa** [comment]
@rmg @sam-github thanks for the info ! I was using arc in the beginning of the project as it was rather useful. I do pretty much all of the work manually now that I understand the project structure.

Thanks for the input.

**Comment by sam-github** [comment]
To be crystal clear: even if you use Arc locally on your machine to do development that in *absolutely no way* means you need arc/strongloop installed on your buildpack when you deploy your app.

An app built with arc is just a normal node/loopback app, you can use the default node.js bluemix buildpack, and `cf push` your arc-built app to it.

**Comment by rmg** [comment]
Released `strong-mesh-client@1.6.5`. You should now be able to do `npm install -g strongloop` without using `--ignore-scripts`.

**Comment by janpansa** [comment]
@rmg Thx ! Awesome !

**Comment by ccoeurderoy** [comment]
@rmg @sam-github Thanks for the info and your quick reaction !

**Comment by sam-github** [comment]
Hey, all thanks are due to @rmg, I looked at it for about half an hour, and couldn't figure out the bizarre deps - the requiring of packages that aren't actually depended on made things fairly hard to understand :-)

@rmg did you report anything upstream? was there a single source of breakage?

**Comment by rmg** [comment]
@sam-github yes, that was the "Up-upstream" I referenced in a previous comment: request/request#2585. I didn't take it any further up stream than that since it was already approaching "a butterfly flapped its wings" level of removal from the actual effect.
