### ISSUE TITLE
Can not register to receive mail

### ISSUE THREAD

**Issue by wanglong167** [strongloop/strongloop#340]
Can not register to receive mail

**Comment by sam-github** [comment]
Hi, I've no idea what you are  trying to report, please add some details (what you did, what you expected).

**Comment by wanglong167** [comment]
https://strongloop.com/register/  
Can't register can't receive the mail

**Comment by wanglong167** [comment]
https://strongloop.com/register/  
Can't register can't receive the mailhttps://strongloop.com/register/  
Can't register can't receive the mail

**Comment by sam-github** [comment]
@sumitha @rmg

**Comment by DaveYVR** [comment]
Are you registering for the newsletter? Just tested that functionality and it works properly.

The link to API Connect should be working as well.

**Comment by rmg** [comment]
@wanglong167 are you seeing any error messages?

**Comment by wanglong167** [comment]
https://github.com/strongloop/strong-arc  How to register account

**Comment by wanglong167** [comment]
Strong-arc subscription Can open source?

**Comment by wanglong167** [comment]
@sumitha @rmg

**Comment by DaveYVR** [comment]
There are no plans to Open Source Arc, and Arc itself has reached end of life and been replaced by API Connect. We recommend Arc users move to the Essentials edition of API Connect. 

Additional details can be found here:

https://strongloop.com/api-connect-faqs/

**Comment by wanglong167** [comment]
tks
