### ISSUE TITLE
Strongloop issue with nsp

### ISSUE THREAD

**Issue by paulcedrick** [strongloop/strongloop#342]
Hi everyone,

It seems that whenever nsp checks strongloop package, it displays this error:
[scan-nsp.txt](https://github.com/strongloop/strongloop/files/1014035/scan-nsp.txt)

Any help would be appreciated :)

**Comment by sam-github** [comment]
strongloop is being deprecated, please use `apiconnect` instead

Also, strongloop is client-side tooling, it isn't a production dependency, so those security issues aren't really relevant.
