### ISSUE TITLE
Implementing geoJson Polygon through loopback...

### ISSUE THREAD

**Issue by aartiCEL** [strongloop/strongloop#345]
Hi,

Loopback has a geopoint type, but we would also need to have the polygon type, and execute geospatial queries... for example: if a certain point lies in a given polygon, or if a point is near my current location. 

Could you please point me to the appropriate documentation/ examples on how this could be used?

Thanks so much,
Aarti

**Comment by sam-github** [comment]
Please ask in one of the developer forums, either gitter or gmail.

http://loopback.io/resources/
