### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by lmyzzu** [strongloop/strongloop#347]
node v8.2.1
verbose npm  v5.3.0
error code EINTEGRITY
error sha1-gkGEMv32K0yFwc5dLpnuL4br1OI= integrity checksum failed when using sha1: wanted sha1-gkGEMv32K0yFwc5dLpnuL4br1OI= but got sha1-ubxPxyg9EdftQMmmAP0SCHbKN60=. (1582009 bytes)
verbose exit [ 1, true ]

**Comment by sam-github** [comment]
This is a problem with your local setup or machine, the tgz fetch via HTTPS from npmjs.org was corrupt. Try again, if its reproducible, look at your network for problems.

Works for me with same node/npm.

Also, not sure why you are still using this package, you should be using the Looback CLI, or `apiconnect`.
